### ISSUE TITLE
 undefined local variable or method `_hamlout`

### ISSUE THREAD

**Issue by amolplay** [haml/haml#1010]
Ruby: 1.9.3-p392
Haml: haml-3.1.7
Rails: 3.2.18

I'm getting this error while browsing site. I tried to modify the method but didn't found the solution for the same.

Any help will be appreciated...

Exception NameError' at /.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/helpers/action_view_mods.rb:181 - undefined local variable or method _hamlout' for #<#Class:0x005576c2fb31a8:0x005576c71fed28>

Exception NameError' at /.rvm/gems/ruby-1.9.3-p392/gems/haml-3.1.7/lib/haml/helpers.rb:543 - undefined local variable or method _hamlout' for #<#Class:0x005576c2fb31a8:0x005576c71fed28>

Exception NoMethodError' at /app/views/devise/sessions/new.html.haml:10 - undefined method control_group' for #ActionView::Helpers::FormBuilder:0x005576c73291a8

**Comment by oniofchaos** [comment]
From the readme, `Haml currently supports Ruby 2.0.0 and higher, so please make sure your changes run on 2.0+.`. Also, changes are only tested on Rails 4+, which is about to lose official support anyway. Also also, you're way behind on Haml itself. 

I would recommend updating some or all of these to try and fix your problem.

**Comment by k0kubun** [comment]
Right. Haml 3 is also not maintained. Please check if the latest Haml works or not first, because we'd need to merge a fix to it and you need to upgrade Haml to that version anyway.
