### ISSUE TITLE
.text.haml files have html escaped content

### ISSUE THREAD

**Issue by cesarizu** [haml/haml#1014]
On haml 5.1.1, all text in `.text.haml` files is html escaped. Using `escape_filter_interpolations` doesn't seem to help. This seems to be related: https://github.com/rails/rails/pull/8235

Is there any way to disable escaping on `text.haml` files altogether?

**Comment by cesarizu** [comment]
PR at haml/haml#1015

**Comment by hcatlin** [comment]
Merged in the PR!
