### ISSUE TITLE
hi, i am new to python and django. i want to resolve the 12 problems shown in studio code.

### ISSUE THREAD

**Issue by crowntech1** [haml/haml#1018]
![New Bitmap Image](https://user-images.githubusercontent.com/57718698/69027070-8ae22200-09f3-11ea-8720-7b0b3110d29c.jpg)

**Comment by crowntech1** [comment]
Hi Friends,
i seek help to know how to resolve the 12 problems shown in visual studio code...
i will be thankful if 112 line is written after correction, i mean somebody writes the correct code it would be best.
thank you

**Comment by k0kubun** [comment]
This repository has nothing to do with Python and Django. Please try going to stackoverflow or a repository of an appropriate project which you're actually using.
