### ISSUE TITLE
uninitialized constant Tilt::ErubiTemplate

### ISSUE THREAD

**Issue by stanley90** [haml/haml#1021]
Upgrading from Rails 5.0 to 5.1, with the following related gems:

```
rails 5.1.7
haml 5.1.2
tilt 2.0.10
```
and `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`

The app fails to boot with `uninitialized constant Tilt::ErubiTemplate`
I found the changes in haml 5.1.1 which seem to address this issue, but it doesn't work for me.

**Comment by stanley90** [comment]
Also, interesting different behavior in `irb` and `pry`

```
$ irb
2.6.5 :001 > require 'tilt'
 => true
2.6.5 :002 > Tilt::ErubisTemplate
 => Tilt::ErubisTemplate
2.6.5 :003 > Tilt::ErubiTemplate
 => Tilt::ErubiTemplate
```

```
$ pry
[1] pry(main)> require 'tilt'
=> true
[2] pry(main)> Tilt::ErubisTemplate
=> Tilt::ErubisTemplate
[3] pry(main)> Tilt::ErubiTemplate
NameError: uninitialized constant Tilt::ErubiTemplate
Did you mean?  Tilt::ErubisTemplate
               Tilt::ERBTemplate
from (pry):3:in `__pry__'
```

**Comment by allantokuda-zipnosis** [comment]
I had this problem specifically here,
```
./.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/haml-5.1.2/lib/haml/helpers/safe_erubi_template.rb:14:in `<module:Haml>': uninitialized constant Tilt::ErubiTemplate (NameError)
```

I found that I needed to update to Tilt >= 2.0.6 where Erubi support was added.
https://github.com/rtomayko/tilt/pull/308

I got Tilt 2.0.10 just like you. Maybe something like `spring` is keeping old gems loaded for you?

**Comment by stanley90** [comment]
I must have missed something when upgrading gems, it really seems to work with Tilt 2.0.10.
Closing, thanks.
