### ISSUE TITLE
haml_tag using :< flag improperly escapes nested tags

### ISSUE THREAD

**Issue by dmeranda** [haml/haml#1024]
As of Haml 5.1.2 —  If you use nested ```haml_tag``` helper methods and the outer one uses the ```:<``` flag to omit internal whitespace or tab indentations, then the inner tag is improperly html-escaped.  Consider:

```
haml_tag :span, :< do
  haml_tag :b, "Hello"
end
```

will generate this raw html:

```
<span>&lt;b&gt;Hello&lt;/b&gt;</span>
```

If you omit the ```:<``` flag it will correctly generate (with whitespace):

```
<span>
  <b>Hello</b>
</span>
```
I expected that using the ```:<``` flag would instead generate:

```
<span><b>Hello</b></span>
```

**Comment by hcatlin** [comment]
Seems like we should maybe support this via an option passed in vs keeping the semantic meaning of "<" in this context?
