### ISSUE TITLE
Haml doesn't work with sass-rails anymore

### ISSUE THREAD

**Issue by Ecco** [haml/haml#1025]
Starting since version 6, the `sass-rails` gem migrated to SassC. As a result, Haml's [sass helper](https://github.com/haml/haml/blob/master/lib/haml/sass_rails_filter.rb) references a class that doesn't exist anymore.

Indeed, the class `Sass::Rails::SassTemplate` has been replaced by `SassC::Rails::SassTemplate`, as defined [in that file](https://github.com/sass/sassc-rails/blob/master/lib/sassc/rails/template.rb).

Unfortunately the required fix is more likely more than just a simple name change.

**Comment by Ecco** [comment]
For what it's worth, here's a quick (and possibly dirty) workaround:

```ruby
module Haml
  module Filters
    remove_filter :Sass

    module Sass
      include Haml::Filters::Base

      @@template = SassC::Rails::SassTemplate.new

      def render(text)
        input = {
          environment: ::Sprockets::Railtie.build_environment(::Rails.application),
          filename: '/',
          metadata: {},
          data: text
        }
        "<style>" + @@template.call(input)[:data] + "</style>"
      end
    end
  end
end
```

**Comment by k0kubun** [comment]
I'm confused. If `app.config.assets.enabled` isn't defined (returns nil) like you said https://github.com/haml/haml/issues/1026, why is `haml/sass_rails_filter` is loaded in your app? Can't we just remove `haml/sass_rails_filter` if it's only accidentally used?

**Comment by Ecco** [comment]
Well `haml/sass_rails_filter` is *not* loaded, as per #1026. But even if it was (and it should), it wouldn't work because Sass' API has changed.
