### ISSUE TITLE
Rails.application.config.assets.enabled doesn't exist anymore

### ISSUE THREAD

**Issue by Ecco** [haml/haml#1026]
In [haml/railtie.rb](https://github.com/haml/haml/blob/598f2b3a364b5601c844db79bf04b387061a396d/lib/haml/railtie.rb#L26) a check is made against `app.config.assets.enabled`.

But this value [isn't defined anymore](https://github.com/rails/rails/issues/10334)

**Comment by hcatlin** [comment]
This seems like something we shouldn't have inside the primary Haml repo anyway. Seems like it should be something handled by `haml-rails`

**Comment by k0kubun** [comment]
Agreed. Both sass-rails (< 6) support and sassc-rails (sass-rails 6) support should go to haml-rails. As this issue proves haml's sass-rails integration is even not used, we can safely remove the integration from haml.gem. Thought maybe that should happen after we prepare a patch to have at least the current sass-rails (< 6) integration in haml-rails.
