### ISSUE TITLE
Ability to accept "/" as class name

### ISSUE THREAD

**Issue by janko** [haml/haml#1027]
TailwindCSS uses the `/` character for some class names (e.g. `w-1/2`), and I noticed that HAML doesn't quite support it:

```haml
.w-1/2
```
```
ActionView::Template::Error (Self-closing tags can't have content.)
    1: .container
    2:   .flex.mt-10
    3:     .w-1/2
```

I'm guessing it clashes with [this feature](http://haml.info/docs/yardoc/file.REFERENCE.html#empty-void-tags-). For now I'm working around it by explicitly using the `:class` option, but it's not ideal.

```haml
.mt-10.bg-white{class: "w-1/2"}
```

Would it be possible for HAML to support `/` as a valid class name character? FYI, I'm using the latest version, 5.1.2.

**Comment by hcatlin** [comment]
Hey @janko–

From my basic research on this topic, it seems that CSS doesn't really fully support `/` in a class name without escaping. You'd have to write the CSS as `.w-1\/2`

Even Tailwind itself ends up [double escaping the output](https://github.com/tailwindcss/tailwindcss/blob/c2b0407ffdc3d6c3cb3323f79d07f7185026532a/__tests__/purgeUnusedStyles.test.js#L30) of the CSS to have that extra escaping. 

I think vs the auto-close tags this would be worse to limit future syntax options for the language if we supported it as specified above... now, what we COULD do is handle this more like CSS by allowing you to do the following:

```
.tailwind
  .w-1\/2 Content
```

Being more CSS-like seems like the right approach here.

**Comment by janko** [comment]
@hcatlin Thank you for the response.

Yeah, the escaping argument makes total sense to me, it would be great if Haml supported `.w-1\/2` 👍

**Comment by hcatlin** [comment]
I'm closing this and opening #1030 with a clearer specification on the bug. Thanks for the report!
