### ISSUE TITLE
Proposal: Remove All Integration Code

### ISSUE THREAD

**Issue by hcatlin** [haml/haml#1031]
@amatsuda @k0kubun @norman @haml/haml-rails @haml/committers 

There is a LOT of code inside of the Haml codebase that is testing compatibility with Rails, various filters, and ActionView specifically.

In 6.0– I would like to move entirely to a Tilt-based integration– and leaning on `haml-rails` for any Rails specific integrations.

Further, on order to get this work done, I propose that after 5.0 is released with the bugfixes as a LTS version, that we quickly move to a 6.0 that is not tested for perfect compatibility with previous versions of Rails.

This project is too large with too many backwards-compatible integrations to possibly move forward easily, hence why I propose a strong forward moving plan.

**Comment by k0kubun** [comment]
> I would like to move entirely to a Tilt-based integration– 

What does this part mean? tilt.gem has Haml's Tilt integration and as of now there's nothing haml.gem can do about Tilt-based integration. Also I believe Tilt doesn't register an ActionView template handler, so we can't _move_ Rails integrations to Tilt at least.

> and leaning on haml-rails for any Rails specific integrations.

I'm in favor of this idea in general, but do you intend to drop all the Rails support from haml.gem, or do you intend to at least register a template handler in haml.gem?

**Comment by hcatlin** [comment]
Right, the ActionView Template handler would be something haml-rails should handle.
