### ISSUE TITLE
Better error message for misaligned HTML tags

### ISSUE THREAD

**Issue by abitrolly** [haml/haml#1036]
```
%section#blog-posts
  <div>
  <div>
    </div>
  </div>
```
This block gives the following error message.
```
Syntax error on line 4: Illegal nesting: nesting within plain text is illegal.
```
I've just spent a day debugging this and decided that it worth a bug report.

The problem with the message is that it is not obvious where the `plain text` is. To me, the markup is the valid HTML with no plain text. It would be nice if Haml parser could detect such cases to give a better error message.

**Comment by hcatlin** [comment]
Sorry you lost a day to this one!

Yeah, this one is tricky. We consider this the exact same as writing the word "Hello" nested inside of there.

We could either... upon seeing this error we could do a quick guess to see if it looks like HTML and just give a better message. OR we could consider in Haml6+ actually supporting HTML as a parsable/structured bit of Haml.

**Comment by abitrolly** [comment]
> Yeah, this one is tricky. We consider this the exact same as writing the word "Hello" nested inside of there.

Like this?
```
%section#blog-posts
  <div>
  <div>
    Hello
  </div>
```
But in this case it is "Hello" what is nested, and not something nested in "Hello" as the message says.
