### ISSUE TITLE
Feature request :) - for / else

### ISSUE THREAD

**Issue by dux** [haml/haml#1037]
The same it is implemented in Svelte https://github.com/sveltejs/svelte/issues/90

It would be nice, if we would be able to write

```
- for el in @model.children
  %p= el.name
- else
 .danger List is empty
```

and not as now

```
- children = @model.children
- if children.first
  - for el in children
    %p= el.name
- else
 .danger List is empty
```

I suggest not to play smart, just if for produces `blank? - true`, use `else` block.

**Comment by k0kubun** [comment]
The function looks nice. However, a problem is that Haml's `-` is converted to a raw Ruby code, and therefore `for`-`else` needs to work to implement this in a reasonable way.

If we support the syntax in Haml level, it'd be compiled to something like:

```rb
for el in @model.children
  puts "<p>#{el.name}</p>"
else
  puts "<div class='danger'>List is empty</div>"
end
```

and it's currently:

```
$ ruby x.rb
x.rb:3: syntax error, unexpected `else', expecting `end'
```

For maintenance reasons and for consistency with Ruby, we may appreciate having the same feature in Ruby's syntax first.

**Comment by hcatlin** [comment]
Propose this to @matz :)

**Comment by matz** [comment]
Use `bugs.ruby-lang.org` to propose a new idea. Although I am not a big fan of Python's `for - else`.
