### ISSUE TITLE
Haml 5 is automatically escaping Angular code with quotes

### ISSUE THREAD

**Issue by raelgc** [haml/haml#1038]
I have the following Angular snippet:

```javascript
%a{'ng-click': "showModal('policies.tpl.html')"}Privacy Policy
```

Which works fine under Haml 4.

I've upgrade to Haml `5.1.2`, and now this is rendered as:

```javascript
<a ng-click='showModal(&#39;policies.tpl.html&#39;)'>Privacy Policy</a>
```

I tried to configure an initializer do not escape stuff like this:

```ruby
# config/initializers/haml.rb

# See more options in the documentation: https://haml.info/docs/yardoc/Haml/Options.html
Haml::Template.options[:escape_filter_interpolations] = false
Haml::Template.options[:escape_html] = false
```

But I still have the same output.

**Comment by hcatlin** [comment]
are you using any frameworks with this?

**Comment by bigethan** [comment]
experiencing something similar but I'm ahead of you version wise (going from Haml 5.1.2 to 5.2.0)...  and it feels related to https://github.com/haml/haml/pull/1015 but not completely sure yet.  It certainly involves apostrophes getting converted to `&#39;` in a javascript template defined in haml where previously they weren't

```ruby
- class_name = "requested-field {{= required ? 'required' : '' }}".html_safe
```

**Comment by raelgc** [comment]
@bigethan After some tests, it worked for me using `escape_attrs`:

```ruby
# config/initializers/haml.rb

# See more options in the documentation: https://haml.info/docs/yardoc/Haml/Options.html
# Haml::Template.options[:escape_filter_interpolations] = false
Haml::Template.options[:escape_html] = false
Haml::Template.options[:escape_attrs] = false
```

**Comment by bigethan** [comment]
ah! nice, seems to be this commit then https://github.com/haml/haml/pull/1028 :-) thanks for the followup!

**Comment by hcatlin** [comment]
Looks like it got solved! <3
