### ISSUE TITLE
:markdown should render triple ``` as code-block <pre><code> but not <p><code>

### ISSUE THREAD

**Issue by kuvaldini** [haml/haml#1046]
Hello folks. Please take a looks at this.
  
    %article
      :markdown
        World hello
        
        ```shell
        this should be a code block highlighted as shell
        ```

            this code block is rendered fine

Is rendered to HTML as:

    <article>
      <p>World hello</p>
      
      <p><code>shell
      this should be a code block highlighted as shell</code></p>
      
      <pre><code>this code block is rendered fine
      </code></pre>
    </article>

I expect second part rendered as:

      <pre lang="shell"><code>shell
      this should be a code block highlighted as shell</code></pre>

I use Middleman on Mac. I think the problem is inside Markdown renderer itself. But have no idea how to change/update it.

**Comment by hcatlin** [comment]
Hi-

First of all, thank you for being a Haml-user, and one that cares enough to actually come open an issue. It's for you that we are doing all of this work here!

Unfortunately for this issue (and a bunch that we are mass-closing) we are stopping active development on the 5.x version of Haml (based on the original Regexp that I wrote 15 years ago). Instead, we will be moving to a totally new engine based on @k0kubun's Hamlit engine. 

It's almost 2x faster than this implementation!

It's an exciting time for this project, and 6.x might not be fully compatible so we're going to slowly be doing preview releases.

I'm going to be closing this issue, but if it still applies to the new Hamlit-based `main` branch, we're happy to consider it.

THANK YOU AGAIN FOR CARING! :) 

And let's make Haml last another 15 years!

**Comment by kuvaldini** [comment]
Hello.
You have make a super cool markup language. It is the ever best way I ever met to describe HTML.
Thanks a lot for your effort.
