### ISSUE TITLE
Multiple multi-line syntax error

### ISSUE THREAD

**Issue by kitebuggy** [haml/haml#1047]
It seems that multiple (2 or more) sequential multi-line methods cause a syntax error.

    = something("something",           |
               {something: something}) |

    = something("something",           |
               {something: something}) |

=> syntax error, unexpected '=', expecting ')'

(I appreciate that multi-line Ruby doesn't require the pipe '|' symbol, but many erb2haml converters seem to create this form of code)

**Comment by hcatlin** [comment]
Hi-

First of all, thank you for being a Haml-user, and one that cares enough to actually come open an issue. It's for you that we are doing all of this work here!

Unfortunately for this issue (and a bunch that we are mass-closing) we are stopping active development on the 5.x version of Haml (based on the original Regexp that I wrote 15 years ago). Instead, we will be moving to a totally new engine based on @k0kubun's Hamlit engine. 

It's almost 2x faster than this implementation!

It's an exciting time for this project, and 6.x might not be fully compatible so we're going to slowly be doing preview releases.

I'm going to be closing this issue, but if it still applies to the new Hamlit-based `main` branch, we're happy to consider it.

THANK YOU AGAIN FOR CARING! :) 

And let's make Haml last another 15 years!
