### ISSUE TITLE
can't escape in js code

### ISSUE THREAD

**Issue by Tealk** [haml/haml#1048]
I would like to include an onClick event, but it is not converting properly.

I have written the following
`%a{:href => "ts3server://TSNAME", :onclick => "_paq.push([\'trackLink\', 'ts3server://TSNAME', 'link']);"}`
converted:
`<a href='ts3server://TSNAME' onclick='_paq.push([&#39;trackLink&#39;, &#39;ts3server://TSNAME&#39;, &#39;link&#39;]);'>`
how it should look:
`<a href="ts3server://TSNAME"  onClick="_paq.push(['trackLink', 'ts3server://TSNAME', 'link']);">`

**Comment by nir9** [comment]
Hi,

You can pass the haml command line option ```--no-escape-attrs``` to show the quotes correctly and you can pass the option ```--double-quote-attributes``` so that the attributes values will be wrapped with double quotes and not single quotes as is being done by default.

**Comment by hcatlin** [comment]
Hi-

First of all, thank you for being a Haml-user, and one that cares enough to actually come open an issue. It's for you that we are doing all of this work here!

Unfortunately for this issue (and a bunch that we are mass-closing) we are stopping active development on the 5.x version of Haml (based on the original Regexp that I wrote 15 years ago). Instead, we will be moving to a totally new engine based on @k0kubun's Hamlit engine. 

It's almost 2x faster than this implementation!

It's an exciting time for this project, and 6.x might not be fully compatible so we're going to slowly be doing preview releases.

I'm going to be closing this issue, but if it still applies to the new Hamlit-based `main` branch, we're happy to consider it.

THANK YOU AGAIN FOR CARING! :) 

And let's make Haml last another 15 years!

**Comment by Tealk** [comment]
Is this the main repo from hamlit?
https://github.com/k0kubun/hamlit
