### ISSUE TITLE
Is nonce support yet?

### ISSUE THREAD

**Issue by guanyun-helo** [haml/haml#1053]
I am adding google analytics to haml but due to content security policy,it is need to add a nonce to inline script.
I have checked doc and could't find nonce about content.

**Comment by hcatlin** [comment]
@guanyun-helo This isn't likely something we'd add to the Haml language itself, BUT depending on how you are compiling Haml, you should be able to write an easy Ruby helper method to generate a nonce on the string of the inline script content.

```
script = "javascript"
nonce = nonce_function(script)
raw "<script nonce=#{nonce}>#{script}</script>"
```

Something like that.

**Comment by guanyun-helo** [comment]
Thanks that's helps a lot.
