### ISSUE TITLE
haml_tag does not accept chained shorthand class names

### ISSUE THREAD

**Issue by matt-whiteley** [haml/haml#1061]
You cannot pass chained class and id shorthand to `haml_tag` e.g. `#foo.bar.baz`

expected
```
haml_tag '#foo.bar.baz'
=> <div id='foo' class='bar baz'></div>
```

actual
```
haml_tag '#foo.bar.baz'
=> <#foo class='bar baz'>
```

It works fine if you specify the element name in addition to the chained classes and id
```
haml_tag 'div#foo.bar.baz'
=> <div id='foo' class='bar baz'></div>
```
It also works fine if you only pass a single class or id.
```
haml_tag '.baz'
=> <div class='baz'></div>
```

Is this intended behaviour? It does not seem like it should be given a major haml feature is not specifying `div`.

---

If this is a bug then the problem is with the regex here: https://github.com/haml/haml/blob/main/lib/haml/helpers.rb#L656

```ruby
# Parses the tag name used for \{#haml\_tag}
# and merges it with the Ruby attributes hash.
def merge_name_and_attributes(name, attributes_hash = {})
  # skip merging if no ids or classes found in name
  return name, attributes_hash unless name =~ /^(.+?)?([\.#].*)$/

  return $1 || "div", AttributeBuilder.merge_attributes!(
    Haml::Parser.parse_class_and_id($2), attributes_hash)
end
```

When multiple classes or ids are passed (`.foo.bar.baz`) then $1 holds the first class `.foo`, not nil. this means the first class in the chain is used as the name of the tag, instead of falling back to `div`. $2 holds the rest of the classes or id chain `.bar.baz`.

When an explicit name and classes are passed `span.foo.bar` then $1 holds `span` and $2 holds `.foo.bar` and it works fine.

When a single class is passed (`.foo`), $1 is nil and $2 holds the class `.foo`, which triggers the `div` fallback and it all works fine.

**Comment by matt-whiteley** [comment]
I believe just excluding `.` and `#` from being allowed in the first match group fixes this, but I have only done a few tests with the code I was personally trying to make work.

`/^([^.#]+?)?([\.#].*)$/`

**Comment by hcatlin** [comment]
Hi-

First of all, thank you for being a Haml-user, and one that cares enough to actually come open an issue. It's for you that we are doing all of this work here!

Unfortunately for this issue (and a bunch that we are mass-closing) we are stopping active development on the 5.x version of Haml (based on the original Regexp that I wrote 15 years ago). Instead, we will be moving to a totally new engine based on @k0kubun's Hamlit engine. 

It's almost 2x faster than this implementation!

It's an exciting time for this project, and 6.x might not be fully compatible so we're going to slowly be doing preview releases.

I'm going to be closing this issue, but if it still applies to the new Hamlit-based `main` branch, we're happy to consider it.

THANK YOU AGAIN FOR CARING! :) 

And let's make Haml last another 15 years!
