### ISSUE TITLE
5.2.1 is broken

### ISSUE THREAD

**Issue by kshnurov** [haml/haml#1062]
A simple `%td{ title: 'Hey' } What's up` fails with `Old attributes must start with "{" and end with "}"` because of that extra ' in the content. 5.2.0 works fine.

**Comment by hcatlin** [comment]
Dang it. Good find.

**Comment by hcatlin** [comment]
Thanks to some great detective work by @k0kubun, we determined that this is only an issue with Ruby 2.4, which has reached it's EOL and represents a bug inside Ripper that will never be fixed.

Closing this issue.
