### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HamptonMakes** [haml/haml#1064]
We need to port over documentation from the 5.x branches so we can still generate docs for the website.

**Comment by k0kubun** [comment]
I didn't replace this in my merge, so it was still Haml 5-based, which means that you should be able to generate docs for the website from it. I gave a first shot of fixing docs obsoleted by Haml 6 https://github.com/haml/haml/commit/83ccbeeeb5d1b50fe4b6acbf901da6b92cb5d682. I think it's enough for now and we could revisit it over time.

**Comment by amatsuda** [comment]
I made some (mostly adhoc) changes on haml-site and haml
https://github.com/haml/haml-site/compare/4ba00b94c8f55183f7efed70f73800c9a5c50c87...4e9cf82ff21e702d2e564fab7a5034be9a4a4b1c
https://github.com/haml/haml/compare/c6e3f85a175d5b41aace36408758a4b0e7052560...f8a96a4e101b8f2a65e930eb8f65c18f99924876

and I think we're now publishing Haml 6 documentation on Haml.info (haven't checked whether the whole contents are up-to-date though)
