### ISSUE TITLE
HAML 6 request for the parser

### ISSUE THREAD

**Issue by MaxLap** [haml/haml#1075]
Hello, I don't know if Haml6 is still going to happen, but if it does, it would be great if the parser could collect more information so that it's possible to better analyze and rewrite it.

In Haml5 for example, this code:

```
- hello(world,
  foo, bar)
```

Will be turned by the parser into `hello(world, foo, bar)` and there basically is no way to know that it was multiple lines or where the line break was other than by manually analyzing the source again. In this case, having a raw source would probably be enough for tools to more easily understand it.

For enabling tooling, such as linters / autocorrecters, this is very important. Rubocop can exist the way it does in great parts because the Parser gem has loads of information about how the code was, the location of parentheses, of operators, etc. Having to rewrite a custom parser is a big wall for tool makers.

**Comment by k0kubun** [comment]
I only maintain the compiler, so honestly it's hard for me to imagine what's needed in the AST for those tooling. Can you make your proposal a pull request? It's something that linter maintainers know better than compiler maintainers, and unfortunately nobody is actively maintaining the parser. You're probably the only person who could contribute this.

**Comment by k0kubun** [comment]
As to Haml 6 mentioned in the issue subject/description, no, the project wasn't about rewriting the parser. We rewrote everything but the parser It's not appropriate to request this to Haml 6, and now that Haml 6 is already released, it's an outdated request too.

I'm going to close this for the above reason. Haml 6 wasn't the version to rewrite the parser, so it's not trivail to make that kind of change there by just "request"ing it. I think this issue should be at least rewritten with the above idea in mind, or just filed as a pull request instead to make what API is necessary crystal clear.
