### ISSUE TITLE
Ruby 3.1 shorthand syntax for attributes?

### ISSUE THREAD

**Issue by mockdeep** [haml/haml#1083]
I'm wondering if there's any intention to support a shorthand syntax for attributes like [the new hash syntax in Ruby 3.1](https://dev.to/baweaver/ruby-3-1-shorthand-hash-syntax-first-impressions-19op). I.e:

```diff
data = { yabba: 'dabba', doo: 'yep' }
-.foo{ data: data }
+.foo{ data: }
```

It's not uncommon for us to pass down `data` or `aria` attributes in particular, so this could provide a little cleaner layout.

**Comment by k0kubun** [comment]
Fixed in v6.1.1.
