### ISSUE TITLE
Will there be any documentation on creating new custom Filters

### ISSUE THREAD

**Issue by braindeaf** [haml/haml#1089]
Our existing filter works in HAML 5 but clearly plenty has changed since.

```
:code
  class Blah < Ruby
  end
```

Using something like this.

```
module Haml
  module Filters
    module Code
      include Base
      extend ActionView::Helpers::TagHelper

      def render(text)
        s = <<CODE
<div class="sa-code-snippet-wrapper">
<div class="sa-code-snippet">
  <div class="code-title">HAML Snippet</div>
  <button class="copy-code-button">Copy</button>
  <pre class="chroma"><code>#{Haml::Helpers.preserve text}</code></pre>
</div>
</div>
CODE
      end
    end
  end
end
```

Failing to make any headway on updating this today. I'm getting a syntax error in the view template.

```
module Haml
  class Filters
    class Code < Base
      def compile(node)
        compile_code(node)
      end

      private

      def compile_code(node)
        temple = [:multi]
        temple << [:static, '<div class="sa-code-snippet-wrapper">']
        temple << [:static, '<div class="sa-code-snippet">']
        temple << [:static, '<div class="code-title">HAML Snippet</div>']
        temple << [:static, '<button class="copy-code-button">Copy</button>']
        temple << [:static, '<pre class="chroma"><code>']
        temple << [:dynamic, Haml::Helpers.preserve(node.value[:text])]
        temple << [:static, '</code></pre></div></div>']
        temple
      end
    end

    register :code, Code
  end
end
```

Many thanks :)

RobL

**Comment by k0kubun** [comment]
I think you meant `s/:dynamic/:static/` in your filter. `:dynamic` is for a Ruby expression and what you're embedding is a Ruby string, which is for `:static`.

Added a reference in the documentation. I'd like future contributors to provide further details if they want.

**Comment by timdiggins** [comment]
Thanks for this addition - looking at existing filters helped.

@k0kubun I think the docs with a tiny example, like the below ( it might be easiest if you just add it -- but if you want a PR, let me know)

> The simplest example of a filter might be something like:

```
class HelloFilter < Haml::Filters::Base
  def compile(_node)
    [:static, "hello world"]
  end
end

Haml::Filters.registered[:hello] ||= HelloFilter
```

> A more complex complex example

class BetterFilter < Haml::Filters::Base
  def compile(node)
    temple = [:multi]
    temple << [:static, "hello "]
    temple << compile_text(node.value[:text])
    temple << [:static, " world"]
    temple 
  end

  private
  def compile_text(text)
    if ::Haml::Util.contains_interpolation?(text)
      [:dynamic, ::Haml::Util.unescape_interpolation(text)]
    else
      [:static, text]
    end
  end
end

Haml::Filters.registered[:better] ||= BetterFilter
```

FYI @braindeaf you might want to look at how `Haml::Filters::Preserve` works rather than using the Helpers.preserve, in case you are using interpolation...

```
      def compile_text(text)
        if ::Haml::Util.contains_interpolation?(text)
          [:dynamic, ::Haml::Util.unescape_interpolation(text)]
        else
          [:static, text]
        end
      end
```

**Comment by k0kubun** [comment]
Can you make it a PR? I don't have bandwidth to write examples for everything while fixing every single bug in master myself and maintaining many other things.
