### ISSUE TITLE
Haml 6: Disabling attributes with false no longer works

### ISSUE THREAD

**Issue by niklas-hasselmeyer** [haml/haml#1091]
From the [docs](https://haml.info/docs/yardoc/file.REFERENCE.html#boolean-attributes):

>To set these attributes to false, simply assign them to a Ruby false value. In both XHTML and HTML,
>```
>%input{:selected => false}
>```
>will just render as:
>```
><input>
>```

However, with Haml 6, I get
```
<input selected="false">
```
which breaks all kinds of stuff

**Comment by k0kubun** [comment]
Can you show how to reproduce it? I can't reproduce it.

```bash
$ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

$ haml version
6.0.1

$ cat /tmp/a.haml
%input{:selected => false}

$ haml render /tmp/a.haml
<input>

$ irb -ruri -rhaml
irb(main)[01:0]> Haml::Template.new { '%input{:selected => false}' }.render
=> "<input>\n"
```

**Comment by k0kubun** [comment]
I'll reopen this once this issue becomes actionable on our end.

**Comment by niklas-hasselmeyer** [comment]
You are right, I didn't check `selected` because I thought that all attributes would be handled as boolean attributes. (My original error was with a custom attribute)
Now it's in the changelog, so I'll rewrite my code.
