### ISSUE TITLE
Documenting "Most Haml helpers are removed."

### ISSUE THREAD

**Issue by brendon** [haml/haml#1092]
I was wondering if there was a list of helpers that were removed from HAML 6? If so, would it be possible to add that to the release notes so that people could quickly search to see if they're using any of them?

**Comment by dentarg** [comment]
This diff may help: https://github.com/haml/haml/commit/330067a8c4a1e3d7def1da99a88fdbf1af078df5#diff-21c5b2122db5dcecc406a281887b41c34483b0efbc7eb8816af469f409c1ad4a

https://github.com/haml/haml/commit/6ff918ece709d3efea71dd5ba608a42d3d4c2fe4 updated the changelog a bit on this subject (though not answering exactly what you asked)

**Comment by contentfree** [comment]
Is there any documentation on what should be used instead of these helpers that were removed?

**Comment by k0kubun** [comment]
No, there wasn't. I added the documentation to the changelog for you https://github.com/haml/haml/commit/d528eecf21fa493a3ff17c53472e62052e12534a.
