### ISSUE TITLE
ruby percentage notation fails to parse

### ISSUE THREAD

**Issue by maland** [haml/haml#1096]
in an haml attribute like title, this works:

`%p{ title: %{foo(#{some_local_variable})} }`

and this as well:

`%p{ title: "foo(#{some_local_variable})" }`

but this does not:

`%p{ title: %(foo(#{some_local_variable})) }`

this raises:

(eval):1: unterminated string meets end of file
%(foo(#)
^

imho all examples are right syntax

**Comment by k0kubun** [comment]
This is technically not this gem's issue but Temple's, but I fixed this in v6.0.4 on Haml's side as it seems like our fix isn't going to be merged to Temple soon.
