### ISSUE TITLE
haml_object_ref missing from v6

### ISSUE THREAD

**Issue by timdiggins** [haml/haml#1097]
REFERENCE.md still has a reference to implementing [`haml_object_ref`](https://github.com/haml/haml/blob/v6.0.4/REFERENCE.md?plain=1#L550-L570)

And this is very useful inside of rails (either with STI and other forms of polymorphic models, and also decorators (Draper and others)) but also outside too.

However it doesn't seem to work and indeed it seems to have disappeared from the code: https://github.com/haml/haml/search?q=haml_object_ref&type=code

```
> git checkout v5.2.2
> grep haml_object_ref **/*.*
CHANGELOG.md:  for a given object by implementing the `haml_object_ref` method on that object.
REFERENCE.md:class, you can implement the `haml_object_ref` method on the object.
REFERENCE.md:      def haml_object_ref
lib/haml/attribute_builder.rb:          if ref.respond_to?(:haml_object_ref)
lib/haml/attribute_builder.rb:            ref.haml_object_ref
test/cases/object_reference_test.rb:    def haml_object_ref

> git checkout v6.0.0
> grep haml_object_ref **/*.*
CHANGELOG.md:  for a given object by implementing the `haml_object_ref` method on that object.
REFERENCE.md:class, you can implement the `haml_object_ref` method on the object.
REFERENCE.md:      def haml_object_ref
test/haml/engine_test.rb:    def haml_object_ref
```

There is no mention of it being dropped in the CHANGELOG.md.

Is there a replacement for this?

If yes, needs some documentation.

If not, can we bring it back? (happy to try a PR but can you give a suggestion of which test file to start with ).

**Comment by k0kubun** [comment]
This removal seems to be not a carefully designed change but an oversight. I just resurrected this feature in 6.0.5.

**Comment by timdiggins** [comment]
Wow - so fast thank you!
