### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by remino** [haml/haml#1101]
Are options gone in Haml?

The link to “options” on the [Documentation](https://haml.info/docs.html) page links to a page without that section.

Searching the Web brings up [a page of options](https://haml.info/docs/yardoc/Haml/Options.html) which does not exist anymore.

**Comment by k0kubun** [comment]
In this repository, we have that section https://github.com/haml/haml/blob/main/REFERENCE.md#options. Can you file a ticket at https://github.com/haml/haml-site instead? Thank you.
