### ISSUE TITLE
How to add a character without spaces after some parsing with HAML 6?

### ISSUE THREAD

**Issue by hacktivista** [haml/haml#1102]
How to add a character without spaces after some parsing with HAML 6?

On HAML 5 we had `succeed`, now IDK how should I do it? I'm not using Rails.

```ruby
= succeed('.') do
  %a{href: '#'} click here
```

Also, I notice HTML is escaped by default now. That should be listed somewhere in the changelog.

**Comment by k0kubun** [comment]
Two options:

### Option 1: Use `>` operator

```haml
%a{href: '#'}> click here
= '.'
```

outputs the same thing as:

```haml
= succeed('.') do
  %a{href: '#'} click here
```

### Option 2: Define helpers yourself
Basically, there's no portable way to define helpers efficiently from a template engine. It should always be specific to web frameworks. We provide some for Rails, but even those should be removed from Haml and delegated to Rails.

For whatever template context you use, just define a helper in there. It should be generally more performant than letting Haml do this in a portable manner.

```rb
def succeed(str, &block)
  "#{block.call.chomp}#{str}\n"
end
```

**Comment by k0kubun** [comment]
> Also, I notice HTML is escaped by default now. That should be listed somewhere in the changelog.

Good catch, done https://github.com/haml/haml/commit/0322d95341cb6a59df4673fd0b5d0d02d82f9d24
