### ISSUE TITLE
Behavior of the element's attributes changed after upgrading to 6

### ISSUE THREAD

**Issue by liram11** [haml/haml#1105]
Hi, I noticed a strange difference in how haml treats attributes after upgrading from 5.2.2 to 6.0.7. 

For example, this line:
```haml
%tagname{"data" => {"required" => "true"}, "data-required"=>nil} Contents
```

Will produce different results.

5.2.2:
```html
<tagname>Contents</tagname>
```

6.0.7:
```html
<tagname data-required="true">Contents</tagname>
```

I didn't find anything about that change in the changelog. Is it expected behavior?

**Comment by k0kubun** [comment]
It's an interesting finding. 

As of the current version, I'd like to say that specifying the same attribute name multiple times is not supported in Haml 6. For example, I guess there's no valid use case to do `%tagname{ :data => true, "data" => false }`, and they look like the same thing to me.

You might have kindly minimized the example code for the issue-reporting purpose, which was indeed helpful, but I'd like to understand why you'd like to do this before re-introducing its support.
