### ISSUE TITLE
HAML 6 : HTML comments no longer interpolate Ruby strings

### ISSUE THREAD

**Issue by mildred** [haml/haml#1107]
With HAML 5 it was possible to get Ruby interpolation within HTML comments:

```haml
/ #{Time.now}
```

Now with HAML 6, the Ruby code is no longer executed

**Comment by mildred** [comment]
Relevant section of the docs : https://haml.info/docs/yardoc/file.REFERENCE.html#ruby-interpolation-

**Comment by k0kubun** [comment]
Thanks, fixed it in 6.0.8.
