### ISSUE TITLE
'ERROR: Failed to build gem native extension' on m1 pro

### ISSUE THREAD

**Issue by chris74er** [haml/haml#1108]
When updating to **6.0.8**, I get the bundler error on the apple m1 pro: **failed to build gem native extension**. With **6.0.6** it works without any problems.

**Comment by dentarg** [comment]
No problem installing 6.0.8 here on Apple silicon (M2):

```
arm64 $ arch
arm64

arm64 $ gem install haml
Fetching haml-6.0.8.gem
Building native extensions. This could take a while...
Successfully installed haml-6.0.8
1 gem installed

arm64 $ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
```

Please check your logs again.

**Comment by chris74er** [comment]
My problem was xcode after i had installed ventura. Just deleted it completely and reinstalled it. Then `xcode-select --install` and it works again! Many thanks.

**Comment by k0kubun** [comment]
:+1: glad it was fixed.
