### ISSUE TITLE
Haml::Engine.new fails to render

### ISSUE THREAD

**Issue by noctivityinc** [haml/haml#1109]
Just upgraded my app to rails 6 and when I try to render a string, HAML fails.  It appears to be due to the expectation of a hash instead of a string in the temple gem:

```
3.1.2 :011 > copy = "this is a string"
 => "this is a string"
3.1.2 :012 > Haml::Engine.new(copy)

/gems/ruby-3.1.2@dmvcs/gems/temple-0.9.1/lib/temple/map.rb:88:in `validate_map!': undefined method `to_hash' for "this is a string":String (NoMethodError)

      map.to_hash.keys.each {|key| validate_key!(key) }
         ^^^^^^^^
Did you mean?  to_haml
```

No idea how to fix this or why it just started

**Comment by noctivityinc** [comment]
FYI, here is my stack:

```
Rails 6.0.5.1
Ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
temple (0.9.1)
```

**Comment by noctivityinc** [comment]
I believe I figured it out, but I had to search the code to find it.  There is no real documentation of this change:

** OLD **
```
return Haml::Engine.new(copy).render(self, options)      
```

** NEW **
```
return Haml::Template.new({}) { copy }.render(self, options).html_safe
```

is that correct?

**Comment by k0kubun** [comment]
Yup, correct. I documented that in https://github.com/haml/haml/commit/83ccbeeeb5d1b50fe4b6acbf901da6b92cb5d682, but I also added that to CHANGELOG. https://github.com/haml/haml/commit/519ef23b55cc5f8b29ecc9849006f272b3d78802

**Comment by Nakilon** [comment]
I wish Google was leading to this thread when you search the error. Had to search via GitHub to find this snippet.
And the indexed docs are outdated -- https://www.rubydoc.info/gems/haml/4.0.1/Haml%2FEngine:render

And while HAML website says "for other options see HAML::Engine", in new docs this doc page is empty https://gemdocs.org/gems/haml/6.3.0/Haml/Engine.html

**Comment by k0kubun** [comment]
If you have suggestions to documents, pull requests would be appreciated. I'm not aware of which part of our document says "for other options see HAML::Engine", and I couldn't find it by searching the repository. I can't fix Google, but the rubydoc website already seems to support the latest one too https://www.rubydoc.info/gems/haml/6.3.0.

**Comment by Nakilon** [comment]
> and I couldn't find it by searching the repository

I meant the main reference page: https://haml.info/docs/yardoc/file.REFERENCE.html

![image](https://github.com/haml/haml/assets/2870363/40f9beb7-b3e3-4843-8cf7-7eea545a8e3d)

When see the `HAML::Engine` there you expect more hints on how to use it but it's a dead end, so maybe that sentence should refer to some another class or wherever those "others options" are.

**Comment by k0kubun** [comment]
Fair enough. I think, when I wrote that part, I literally meant "see `Haml::Engine`" as in reading its source code. Right now it's specifically about https://github.com/haml/haml/blob/v6.3.0/lib/haml/engine.rb#L16-L29, but the line numbers may change over time, so I linked to a whole file at https://github.com/haml/haml/commit/ea151974096247daf8fc7b6ce360364068522b35.

It may take a while for https://haml.info/ to reflect the change, but please report issues to https://github.com/haml/haml-site if it happens.
