### ISSUE TITLE
Haml_6 and `ng-*` rendering: quick questions

### ISSUE THREAD

**Issue by jibees** [haml/haml#1110]
Hello!
I tried to upgrade to Haml 6 (I'm currently running on Haml 5), and I observe that 
```haml
%a{ ng: { href: "mailto:{{order.email}}" } }
```

is transformed to 
```html
<a ng-href="mailto:EMAIL" class="ng-binding" href="mailto:EMAIL">
```
with Haml 5 

but transformed to
```html
<a ng="{:href=>&quot;mailto:EMAIL&quot;}" class="ng-binding">
```

with Haml 6.

What am I missing? 

Thanks a lot ;)

**Comment by jibees** [comment]
If I modify my orginal haml file to
```haml
%a{ "ng-href": "mailto:{{order.email}}" }
```

it's well transformed to 
```html
<a ng-href="mailto:EMAIL" class="ng-binding" href="mailto:EMAIL">
```

but I don't want to change all the 906 occurrences of `ng: ` on my project (if possible ...)

**Comment by jibees** [comment]
Even with JS disabled (ie. without interaction with AngularJS) the following html:

```html
%a{ng: {'click': "method()"}}
```

is transformed to:
```haml
<a ng-click="method()">
```
with haml 5

and is transformed to:
```haml
<a ng="{:click=>&quot;method()&quot;}">
```
with haml 6

**Comment by k0kubun** [comment]
This is an intended change that was necessary for optimization. I added a changelog entry that explains it https://github.com/haml/haml/commit/dbc4ff6b52b368136bea9a13d6ab1537942ec571. 

`%a{ ng: { href: "mailto:{{order.email}}" } }` needs to be changed to `%a{ "ng-href": "mailto:{{order.email}}" }`.

**Comment by jibees** [comment]
Ok, thanks a lot for your answer.
