### ISSUE TITLE
HAML 6 - :erb filter wrong context

### ISSUE THREAD

**Issue by krisdigital** [haml/haml#1113]
When using the `:erb` filter, the context is an empty object instead of `ActionView::Base`

This crashes:

```
- foo = "bar"
:erb
  <%= foo %>
```

I noticed, that the test is skipped: https://github.com/haml/haml/blob/8b336d4e43f0a73020b8ef95c17eabc7921c7831/test/haml/filters_test.rb#L129

Will the filters be supported again in the future?

Thank you 🙏

**Comment by k0kubun** [comment]
Fixed in v6.0.10.

**Comment by krisdigital** [comment]
@k0kubun WOW!!! Thank you for the incredibly quick fix and gem release! 🤩🙏
