### ISSUE TITLE
Some forms of prefixed attribute specification don't work (anymore - in Haml6)

### ISSUE THREAD

**Issue by timdiggins** [haml/haml#1115]
When specifying prefixed attributes there are several ways that work in both Haml5 and Haml6

e.g. to generate

```html
<div data-tags-url-value='http://example.com'></div>
```

You can do

```
%div(data-tags-url-value="http://example.com")
%div{"data-tags-url-value"=>"http://example.com"}
```

or

```
- data = {"tags-url-value" => "http://example.com"}
%div(data=data)
%div{data: {"tags-url-value" => "http://example.com/4"}}
```

However there are some ways that work in Haml5 but not in Haml6

```
- data_tags = {"url-value" => "http://example.com"}
%div(data-tags=data_tags)

%div{"data-tags": {"url-value" => "http://example.com"}}
```

In Haml6 these become

```html
<div data-tags='{&quot;url-value&quot;=&gt;&quot;http://example.com&quot;}'></div>
```

Would there be an easy fix for this? Or if not, a succinct way to describe what does and doesn't work?

PS I rarely find myself **needing** to use this last way, but some legacy code has ended up using this.

References:

> Any entry in an attribute hash that has a Hash as its value is expanded into a series of attributes, one for each key/value pair in the hash

https://haml.info/docs/yardoc/file.REFERENCE.html#prefixed-attributes

**Comment by k0kubun** [comment]
This is intended, so updated the reference about this https://github.com/haml/haml/commit/828f29e1ae3ea03ffceb606f50e34cbceb9712fb. See also: https://github.com/haml/haml/issues/1110#issuecomment-1304710195

**Comment by timdiggins** [comment]
Thanks very much for the clarification in the docs. Very understandable now.
