### ISSUE TITLE
Textile support ?

### ISSUE THREAD

**Issue by zbynek** [haml/haml#1129]
With Haml5 it was possible to do `Haml::Filters.register_tilt_filter "Textile"`. This is stil present in tests, but only to check that it throws an error. It might be helpful to somehow document whether/how using Textile with new Haml is still possible.

**Comment by k0kubun** [comment]
Would you mind filing this in https://github.com/haml/haml-contrib instead? That repository probably doesn't work for the current Haml, but we should discuss Textile support there since that repository has supported it (for old Haml versions).
