### ISSUE TITLE
Documentation: update changelog and new releases

### ISSUE THREAD

**Issue by tagliala** [haml/haml#1130]
Hi, would it be possible to:

- [ ] Regenerate docs at https://haml.info/docs/yardoc/file.CHANGELOG.html (it stops at 6.0.7)
- [ ] Add the missing releases at https://github.com/haml/haml/releases (they stop at 6.0.1)

I think it is not possible to contribute to this request with a PR

**Comment by k0kubun** [comment]
I did the second one. The first one is reported to the wrong repository; maintainers of this repository (like me) don't necessarily have permission to update that. Would you mind filing it at https://github.com/haml/haml-site instead?
