### ISSUE TITLE
Please contribute Temple filters upstream

### ISSUE THREAD

**Issue by minad** [haml/haml#1131]
I've seen there are multiple filters used by Haml. Could you tell me for which it would make sense to have them in Temple too? Which could potentially be useful in other Gems too?

- [ ] StringSplitter
- [ ] Escape
- [ ] EscapeAny
- [ ] ForceEscape
- [ ] Whitespace
- [ ] DynamicMerger

**Comment by k0kubun** [comment]
> StringSplitter

Your list includes one that has already been upstreamed. So `StringSplitter` and `StaticAnalyzer` are the ones that were originally created for Hamlit but then upstreamed. 

As to `Escape`/`EscapeAny`/`ForceEscape`, it's kinda specific to weird Haml behaviors. If Slim is going to introduce the exact same behavior and wants to share some of these, I'm fine with that, but do you really need them? Sharing engine-specific logic may not necessarily help each other.

`DynamicMerger` is one that was added long after those two filters, and it probably makes sense to upstream as a general optimizer. I filed a pull request at https://github.com/judofyr/temple/pull/147.
