### ISSUE TITLE
Incoming breakage from rails main for haml v5

### ISSUE THREAD

**Issue by kyrofa** [haml/haml#1134]
The main branch on rails [recently broke TagHelpers in haml v5](https://github.com/rails/rails/issues/47443). It doesn't seem to be an issue in haml v6, but I wanted to give you folks a heads up in case that was something you might want to fix for v5.

**Comment by k0kubun** [comment]
Thanks for reporting this. We don't even maintain the branch for v5 anymore, so please consider upgrading Haml to v6 if you're interested in making it compatible with Rails main.
