### ISSUE TITLE
Upgrade problem on one computer (windows) on server (linux) all seems ok

### ISSUE THREAD

**Issue by Bodata** [haml/haml#1135]
I did a 'bundle update' and it made the haml gem go from 5.x to 6.x
In this version Haml::Engine was replaced with Haml::Template    

I first made a change on the production server (linux) all seems to work ok.

```` 
old:
  haml_engine = Haml::Engine.new(template)
   
new:
  haml_engine = Haml::Template.new{template}
````
When i made the same fix on my development machine i got 

````
undefined local variable or method `metadata' for #<Haml::Template:0x000000000990e198>

`````
I have been searching but i cannot find any usefull pointer to this problem.

Wat is happening here ?

Regards,
Peter

**Comment by k0kubun** [comment]
I don't see any `#metadata` method in this repository, so I'm afraid it's something that was removed during the v6 migration. Whatever is the caller of that method (which is not shared in the issue description), please consider updating the caller to stop calling `metadata`.
