### ISSUE TITLE
haml_io in ruby filter missing

### ISSUE THREAD

**Issue by creativetags** [haml/haml#1136]
I upgraded to haml 6.1.1 from 5.2.2 and got an error that haml_io is undefined. I was using it to output the result of some ruby code. The docs haven't been updated if this has been deprecated. How do I output from :ruby filter now? 

Last occurrence of the code:
https://github.com/haml/haml/blob/31727c9af7795f7997b4eca8f81343d84df9175a/lib/haml/filters.rb#L288

Still referenced in latest docs:
https://github.com/haml/haml/blob/main/REFERENCE.md#ruby-ruby-filter

**Comment by mattscilipoti** [comment]
Any guidance on how we should render ruby now? As a workaround, I'm assigning it to a variable in the ruby filter and then rendering the variable, outside the ruby filter.

**Comment by k0kubun** [comment]
This was a documentation error. I'm sorry. I updated the reference in https://github.com/haml/haml/commit/fa8fe03d004576bb1205561db8a8b4a786f4a635.

> Any guidance on how we should render ruby now? As a workaround, I'm assigning it to a variable in the ruby filter and then rendering the variable, outside the ruby filter.

I think the "workaround" looks fine. I do something similar too.

v6 is designed to generate optimal compiled code, and I'm afraid supporting the `haml_io` interface would likely sacrifice the performance. The code generated by your `:ruby` code is exactly what I would like to generate in the end, and your code generates that in a way that everybody can easily understand.
