### ISSUE TITLE
RDFa doctype no longer works

### ISSUE THREAD

**Issue by dub357** [haml/haml#1147]
Starting in 6.0.0, the `!!!RDFa` doctype referenced here (https://haml.info/docs/yardoc/file.REFERENCE.html#doctype-) no longer works (even if the format is specified as :xhtml) and view compilation results in an error:
`ActionView::Template::Error (Invalid doctype rdfa)`

I have found no work-arounds other than changing the doctype to something else completely.

**Comment by k0kubun** [comment]
Fixed in v6.2.3.

**Comment by HamptonMakes** [comment]
Whoa... I have so many questions about your app!
