### ISSUE TITLE
6.2.0 regression with nested arrays in class attribute

### ISSUE THREAD

**Issue by javinto** [haml/haml#1151]
Our code contains lines like:

`%div{class: ['col', extra_cols]}`

where extra_cols could be another array like ['col-md-6', 'col-lg-8']. 

Until version 6.2.0 this was parsed as:  `<div class="col.col-md-6.col-lg8">`

From version 6.2.0 onwards it is parsed as: `<div class="col ['col-md-6', 'col-lg-8']">`

Is this change meant to be?

**Comment by mak-dunkelziffer** [comment]
Fixing that on Haml's side would require to always call `#flatten` on the array. This might be a performance hit. Would it work to explicitly splat the array everywhere?
```ruby
%div{ class: ['col', *extra_cols] }
```

**Comment by javinto** [comment]
It would definitely work if we would splat it in our application. But offcourse that means work. So I just want to know for sure if the that's the new HAML policy before I make any unnecessary changes. Eventually we will benefit too from any performance increases in all those cases where no splat is needed (most cases).

**Comment by mak-dunkelziffer** [comment]
I'm not part of the Haml team. I can't answer that. But overall it seems like Haml 6 is introducing more conventions to do less work at runtime.

**Comment by javinto** [comment]
Thank you both for your reactions. I guess that splatting on our site would be a safer idea, also for future versions. I will close this issue.
