### ISSUE TITLE
issue introduced in Haml 6.1.3 with using fallback (or specific non-html) format alternative

### ISSUE THREAD

**Issue by timdiggins** [haml/haml#1154]
If you define custom formats / mime types e.g.

```
Mime::Type.register "application/xls", :xls
Mime::Type.register_alias "text/html", :raw
```

and then define layouts and partials based on a generic/fallback format (`views/layouts/application.{erb,haml}` and e.g.`views/things/_thing.{erb,haml}`).

so you have files (taking the haml view)

```
app/views/layouts/
  application.haml
  application.html.haml

app/things/
  _thing.haml
  _thing.html.haml
  show.haml
  show.html.haml
```

then working with this in haml 5 or haml 6.0 - the selection is made as expected/same as erb (.raw and .xls choose the one without .html, whereas .html choose the one with .html), ie.

* `app/things/show.haml`
* `app/things/_thing.haml`
* `app/layouts/application.haml`

but when you move to haml 6.1 the selection is made as follows:

* `app/things/show.html.haml`
* `app/things/_thing.haml`
* `app/layouts/application.html.haml`

## Screenshots

Expected .html
![test_visiting_as_html](https://github.com/haml/haml/assets/18395/f0b8acf0-edf1-4c67-bff8-dff2c29ce698)

Expected .raw (erb, haml-5, haml-6.0, haml-6.1.2)
![test_visiting_as_raw](https://github.com/haml/haml/assets/18395/4ee7785d-a3ec-4050-afee-ca1801b272cf)

Got .raw (haml-6.1.3+)
![test_visiting_as_raw-haml-6 1 3](https://github.com/haml/haml/assets/18395/82fb640e-b81a-47fc-8af4-6ac52b1b2962)

## reproduction repo

see https://github.com/timdiggins/haml-issue-1154

main branch is erb, separate branches for different haml versions

`rails test:all`

**Comment by k0kubun** [comment]
Removed `#default_format` in v6.3.0.
