### ISSUE TITLE
Template broken with TruffleRuby 24.0.1

### ISSUE THREAD

**Issue by n-rodriguez** [haml/haml#1161]
Hi there! I'm trying to run a Rails application with TruffleRuby 24.0.1 and the rendering is partially broken.

Here a screenshot :
![Screenshot 2024-05-13 at 02-08-04 #{( Haml Util escape_html_safe((_haml_compiler1))) to_s}](https://github.com/haml/haml/assets/3433835/aad7fbe3-e2ae-48c0-90e4-afee82d619db)

The app runs perfectly with Ruby 3.3.1.

I'm running `haml 6.3.0`: 

```sh
nicolas@MacBook-Pro-de-Nicolas:~/PROJECTS/CONCERTO/concerto$ grep haml Gemfile.lock
    haml (6.3.0)
```

Thank you!

**Comment by HamptonMakes** [comment]
Seems like our tests for TruffleRuby have been failing:
https://github.com/haml/haml/actions/runs/9210369754/job/25337217627#step:5:52

**Comment by dentarg** [comment]
Can you test with TruffleRuby-head build? We had similar failures in https://github.com/sinatra/sinatra/issues/2007 and there was a bug https://github.com/ruby/prism/issues/2646 that will be included in a later TruffleRuby release.

**Comment by n-rodriguez** [comment]
@dentarg TruffleRuby 24.1.0 is out and the problem is fixed. Thank you!
