### ISSUE TITLE
Does HAML rebuild when a sass mixin changes?

### ISSUE THREAD

**Issue by winstonwolff** [haml/haml#1162]
So far this is more a question rather than an issue—I'm trying to track down if my problem is my configuration, a haml bug, or a sass bug.

My question is: if a HAML file has an `:scss` section, and that `@includes` a mixin, when I change the mixin file, will haml detect that and rebuild the `<style>` section of the HTML page?

Here's an illustration:

Say I have index.haml which uses the `salmon_background_mixin`. If I change the definition of the mixin so the color is "plum" instead of "salmon" in `_my_mixins.scss`, and I reload my browser, the color change does not appear. But if I add a blank line to `index.haml` to cause it to be rebuilt, then I see my color change. I.e. a change to the included file is not picked up as a dependency by haml. Is this expected?

```
# index.haml

:scss
  @import "my_mixins";

  div.salmon_colored {
    @include salmon_background_mixin;
  }
```

```
#_my_mixins.scss

@mixin salmon_background_mixin {
  background-color: salmon;
}
```

**Comment by niklas-hasselmeyer** [comment]
No, HAML does not detect changes to imported files.

HAML itself does not detect changes to files at all, that is done by ActionView. HAML only compiles the file once for the first render. ActionView then only fills in the values of your variables and dynamic code for each render without recompiling the . If a file in your views folder changes, that cache is cleared.

This construct makes the assumption that the result of compiling the inlined sass code does not change when the file itself is untouched. This has the advantage that SASS code does not have to be recompiled for every render, which saves render time.

If you want to change that temporally, you could add an empty interpolation `#{}` to the scss string, then the sass is recompiled on every render.  
Alternatively, you could also set
```
config.action_view.cache_template_loading = false
```
in development.

**Comment by winstonwolff** [comment]
I suspected as much. Thank you Niklas.

**Comment by HamptonMakes** [comment]
I'm embarrassed to say that I'm surprised (and interested) to find out that @import of mixins works with a filter usage of :scss!

But yeah, @nhasselmeyer is totally correct in their answer.

**Comment by winstonwolff** [comment]
> I'm embarrassed to say that I'm surprised (and interested) to find out that @import of mixins works with a filter usage of :scss!

Yeah I was very excited to get it working. It took a lot of trial and error to get the paths right.
