### ISSUE TITLE
No command line output in haml 6 with `puts`

### ISSUE THREAD

**Issue by sven1904** [haml/haml#1164]
In haml 5, I used to print some info to command line using `puts` while converting my haml file to html.
Unfortunately, this seems to be impossible in haml 6 since every call to `puts` is also rendered into the resulting html instead of printed on the command line.

Do I miss something here, or is this really not possible anymore?

**Comment by nhasselmeyer** [comment]
I can't reproduce the behavior you're describing. With Haml 6, the template
```
.bar
  - puts 'foo'
  = 'baz'
```

renders to the HTML `<div class='bar'>baz</div>` and prints `foo` on the console.

**Comment by sven1904** [comment]
that would also be what i would expect, but:
``` bash
$ cat baz.haml
.bar
  - puts 'foo'
  = 'baz'
$ haml baz.haml > baz.html 
$ cat baz.html 
foo
<div class='bar'>
baz
</div>
$ haml version
6.3.0
```
I don't know if it makes a difference, but I'm on ubuntu 24.04.

**Comment by nhasselmeyer** [comment]
I think everything works as intended.

The thing that you're seeing is:
- `puts 'foo'` writes `foo` to STDOUT
- Haml writes the rendered html `<div class='bar'>\nbaz\n</div>` to STDOUT
- All output is concatenated and written to baz.html

If you use `STDERR.puts` instead, `foo` is written to STDERR and baz.html should only contain the rendered HTML

**Comment by sven1904** [comment]
Interesting, since it was working that way in my old system (ubuntu 20.04 with haml 5.x).
But totally makes sense, now when I think about it.

Anyway, thanks for the help.

If anyone has a similar "problem", I just wrote a small script that I use now instead of calling `haml` from the command line:
``` ruby
#!/bin/ruby

require 'fileutils'
require 'haml'

file = ARGV.first.delete_suffix(".haml")
html = Haml::Template.new{File.read("#{file}.haml")}.render
FileUtils.mkdir_p("build")
File.write("build/#{file}.html", html)
```
