### ISSUE TITLE
CI: Failures against Ruby 3.4 (PR attached)

### ISSUE THREAD

**Issue by tagliala** [haml/haml#1173]
### Failing specs

https://github.com/haml/haml/blob/3841f56a8005bebcd89ee11de6afcd34f1f4abcb/test/haml/engine/old_attribute_test.rb#L185

https://github.com/haml/haml/blob/3841f56a8005bebcd89ee11de6afcd34f1f4abcb/test/haml/engine/text_test.rb#L9

### Related actions

Happened between 

```
ruby 3.4.0dev (2024-09-28T13:37:44Z :detached: b9e225fcbf) +PRISM [x86_64-linux]
```

https://github.com/haml/haml/actions/runs/11182286904

and

```
ruby 3.4.0dev (2024-10-04T19:04:26Z :detached: 30038656aa) +PRISM [x86_64-linux]
```

https://github.com/haml/haml/actions/runs/11194167831

### Investigation

Bisected to: ruby/ruby@a8a059125314a411eaf879a9fbfdc68d6c01a667

Refs:
- rails/rails#53202

**Comment by tagliala** [comment]
I won't propose a pull request because the fix is trivial, but that's assuming the change is limited to the tests. I'm not confident there won't be unintended consequences in the library's core functionality.

**Comment by dentarg** [comment]
Looking at the changes you made in https://github.com/tagliala/haml/commit/9237d6c51f116e7a9f004fc1192d28f33c0c46f1, my thinking is that it is limited to the tests and that Haml the library doesn't depend on this `Hash#to_s`. Sure there will be a change in the output for users, when they use the new Ruby version. That's life.

I think it would be good to open the pull request for this!

```ruby
$ chruby 3.3

$ irb
irb(main):001> puts({ foo: "bar" }.to_s)
{:foo=>"bar"}

$ chruby 3.4

$ irb
irb(main):001> puts({ foo: "bar" }.to_s)
{foo: "bar"}
```

**Comment by dentarg** [comment]
> I think it would be good to open the pull request for this!

I guess a PR would have to account for both old and new ruby versions though.

**Comment by tagliala** [comment]
> I guess a PR would have to account for both old and new ruby versions though.

Thanks, in fact it was failing with older Ruby versions

Now it is not failing anymore, but I don't know which one should be the correct approach

- hardcoded string, conditional in template
- helper relying on `Hash#inspect` which works on both (current implementation)
- helper that returns a hardcoded string given a key and a value

**Comment by tagliala** [comment]
Proposing a PR, since Ruby 3.4 is now stable
