### ISSUE TITLE
Sass compile failing on Unicode character

### ISSUE THREAD

**Issue by dparis** [haml/haml#269]
System:  FreeBSD 8.1-RELEASE AMD64-GENERIC
Ruby:  rvm installed 1.9.2p0 (2010-08-18 revision 29036) [x86_64-freebsd8.1]
haml/sass:  gem version 3.0.18 (Classy Cassidy)

Using the Compass gem version 0.10.5 with the susy plugin, whenever I go to compile a susy-based compass project my compiled CSS shows a stack trace indicating the following:

```
Syntax error: Invalid US-ASCII character "\xE2"                                 
        on line 19 of /home/admin/.rvm/gems/ruby-1.9.2-p0/gems/compass-0.10. /frameworks/compass/stylesheets/compass/css3/_font-face.scss
```

This file contains a mixin which generates a font-face rule using Paul Irish's smiley hack for local font file overrides, as defined here: http://paulirish.com/2009/bulletproof-font-face-implementation-syntax/#smiley

**Comment by geoidesic** [comment]
I wish someone would say how they changed LANG=en_US.UTF-8 instead of just saying that they did it.

**Comment by Grawl** [comment]
@geoidesic you have to modify your `.bashrc` or `.profile` (maybe `.zshrc` if you use ZSH).

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by mrthehud** [comment]
I get this error using sass & assetic, with symfony ("Error: Invalid US-ASCII character "\xEF"").

I'll add that setting LANG alone didn't help, and I had to set LC_ALL, as mentioned by Grawl above, as well.

**Comment by m-hagberg** [comment]
For the record, it's not `@charset: "UTF-8"` in CSS - it's actually typed without quotation marks, `@charset UTF-8;`.

**Comment by DrParanoia** [comment]
What helped me was `locale-gen en_US.UTF-8 && export LANG=en_US.UTF-8`. My encoding kept breaking if at least one of these commands is omitted.
