### ISSUE TITLE
Multiline appends extra whitespace

### ISSUE THREAD

**Issue by enosis** [haml/haml#295]
```
%div
    First line |
    Second line |

<div>\n  First line Second line \n</div>
```

This and other multiline oddities are explored in the Haml Whitespace Semantics Extension (Haml WSE) proposals at commit enosis/text-haml@386c0cd124fc96ff3173027644077d8b16f32878.

See:
-   [WSE Haml](http://github.com/enosis/text-haml/blob/wip-wse/doc/Haml_WhitespaceSemanticsExtension_ImplementationNotes.md)
-   [Html Multiline RSpec](http://github.com/enosis/text-haml/blob/wip-wse/ruby/spec/09multiline_spec.rb)

**Comment by k0kubun** [comment]
This issue may be about pretty mode, which is removed in Haml 4. Feel free to reopen this if it's not the case.
