### ISSUE TITLE
Haml escapes &amp; into &amp;amp

### ISSUE THREAD

**Issue by enosis** [haml/haml#296]
```
:escape_html => true
%p= "this & but not &amp; that

<p>this &amp; but not &amp;amp; that</p>
```

The same results obtain via other 'preserve' facilities, such as filter:preserve and ~.

This and other escape oddities are explored in the Haml Whitespace Semantics Extension (Haml WSE) proposals at commit enosis@386c0cd124fc96ff3173027644077d8b16f32878

See:
-   [WSE Haml Implementation Notes](http://github.com/enosis/text-haml/blob/wip-wse/doc/Haml_WhitespaceSemanticsExtension_ImplementationNotes.md)
-   [Html Html Escaping RSpec](http://github.com/enosis/text-haml/blob/wip-wse/ruby/spec/11htmlescaping_spec.rb)

**Comment by k0kubun** [comment]
I think this is expected behavior. If you really want to do that, you should write:

```haml
%p!= escape_once("this & but not &amp; that")
```
