### ISSUE TITLE
Syntax error: Invalid CSS after "@include ": expected identifier, was ""reset";"

### ISSUE THREAD

**Issue by pib** [haml/haml#334]
```
Syntax error: Invalid CSS after "@include ": expected identifier, was ""reset";"
        on line 1 of media/css/base.scss
  Use --trace for backtrace.
```

Run with --trace, it also adds this:
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:821:in `expected'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:796:in`expected'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:792:in `tok!'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:140:in`include_directive'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:129:in `send'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:129:in`special_directive'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:108:in `directive'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:339:in`block_child'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:330:in `block_contents'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:57:in`stylesheet'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/scss/parser.rb:26:in `parse'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/engine.rb:283:in`_to_tree'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/engine.rb:262:in `_render'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/sass/engine.rb:233:in`render'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/haml/exec.rb:294:in `process_result'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/haml/exec.rb:41:in`parse'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/../lib/haml/exec.rb:21:in `parse!'
        from /home/pib/.gem/ruby/1.8/gems/haml-edge-3.1.79/bin/sass:8
    from /home/pib/.gem/ruby/1.8/bin/sass:19:in`load'
        from /home/pib/.gem/ruby/1.8/bin/sass:19

I get this error when running

```
~/.gem/ruby/1.8/bin/sass --scss media/css/base.scss:base.css
```

Currently, base.scss just includes one line:

```
@include "reset";
```

I've tried the version I get from running "gem install haml" as well as "gem install haml-edge", with the same result.

**Comment by caumons** [comment]
:+1:

**Comment by alekseypetrenko** [comment]
same error ))) thx @pib
