### ISSUE TITLE
method_missing in a helper can break unrelated views

### ISSUE THREAD

**Issue by rgarner** [haml/haml#339]
Hi,

Just came across a fairly strange issue in 3.0.25 (which I think is Haml because when I revert to Erb the problem goes away) when I use a helper which implements `method_missing` to return a value (bad practice, I've come to think, and I'm avoiding it now but I put it up here because it took me a long time to figure out why).  The problem seems to stem from `helpers.rb:540`, where `_hamlout` is evaluated with a rescue to determine if the `block_is_haml?`.

I've tarred up a project at http://zephyros.co.uk/downloads/haml_form_breaker.tar.gz that demonstrates the issue with a single spec.  I try to use `form_for` in a Haml template for a view associated with the (non-)model Cota, but the presence of the `method_missing` in the unrelated `ContactsHelper` causes the Haml template generation to fail because of `block_is_haml?`.  It seems that somehow unrelated helpers are being mixed in, but I can't see how.

I'm avoiding the problem for now by wrapping any `method_missing`-style helper in an intermediate class, but I wondered if this was just me being stupid or a genuine problem with helpers being cross-wired.

**Comment by k0kubun** [comment]
As far as I know, Haml does no longer have `method_missing` in implementation. Closing.
