### ISSUE TITLE
HAML doesn't work with HTTP streaming.

### ISSUE THREAD

**Issue by juliosantos** [haml/haml#436]
There appears to be an issue with using HTTP streaming with HAML projects in rails. It works perfectly if I use ERB instead.

It doesn't work with placing stream at the top of the controller, or with using render :stream => true in the action.

**Comment by hcatlin** [comment]
6 years and no action.... I'm not even 100% familiar with streaming in Rails these days, so let's call this closed for now– any modern examples would be well appreciated.
