### ISSUE TITLE
Feature: ignore indents within -# comment

### ISSUE THREAD

**Issue by jasonkuhrt** [haml/haml#464]
Logically, I would expect that any indents under `-#` get ignored. Two reasons:
- it makes block-comments meaningfully easier to use
- it is logical to ignore the indentation because the nested content could have no other use

Here's a use-case with documentation:

```
-#
-#      optional locals:
-#      :list_class         <string>    Inserted into the containing ul element "class" attribute
-#      :item_partial       <string>    Overrides default item_partial, selecting from /partials/list/items/<your_argument>.
-#                                      If the item_partial contains a slash, it is assumed to be a full path to the partial relative
-#                                      to app/views. If it doesn't, then its a partial in partials/list/items/.
-#
-#      required locals:
-#      :collection
```

In the above I am forced to comment every line because the two indented lines (under `:item_partial`) would throw an error in a block-comment context.

**Comment by joelpresence** [comment]
I just encountered this in Haml 4.0.7 and it's very frustrating.  I expect everything inside a `-#` comment to be ignored and indentation to be ignored.  Further, I just took code whose indentation worked fine, then indented it a bit inside a Haml comment and now haml is barfing with a message that makes no sense to me `Inconsistent indentation: 21 spaces used for indentation, but the rest of the document was indented using 2 spaces.`.  Can we please re-open this issue and fix this?

Thanks!
