### ISSUE TITLE
Default format under Rails 3 prevents the use of multiple doctypes in an app

### ISSUE THREAD

**Issue by lukesutton** [haml/haml#473]
Currently HAML under Rails 3 the `:format` option defaults to `:html5`. This can be overridden with an initialiser if necessary.

Unfortunately, using the `:format` option means you cannot use HAML to render different documents with different doctypes. For example I cannot have a XHTML front-end and a HTML5 back-end. It is one format or the other.

**Comment by k0kubun** [comment]
Yes. Unfortunately Rails/ActionView doesn't provide option to switch configuration per templates.

We need to address this problem in https://github.com/haml/haml/issues/775 or another way. Closing in favor of that issue.
