### ISSUE TITLE
Rendering extra whitespace (&#x000A;) in textarea, input in Rails 3.2.3

### ISSUE THREAD

**Issue by pelcasandra** [haml/haml#516]
I'm getting by default an extra whitespace `&#x000A;` inside every textarea or input fields.

```
<textarea class="textarea" cols="50" id="idea_idea" name="idea[idea]" rows="2">&#x000A;</textarea>
```

Check this issue here,
http://stackoverflow.com/questions/10370948/extra-whitespace-when-rendering-a-text-area-in-rails-3-2-3

**Comment by randoum** [comment]
Hi,
Still affecting 4.0.6, is there any solution? @gmcintire workaround is not working for me
Thanks and regards

**Comment by norman** [comment]
@randoum Can you show us the code that's causing this to happen so we can reproduce it locally?

**Comment by randoum** [comment]
@norman, please see bellow. It is a very simple piece of code

```
= form_for [:cms, @template], novalidate: true, class: 'form-horizontal', role: 'form', remote: true do
  = f.text_area :description
```

With migration for the model
```
class CreateTemplates < ActiveRecord::Migration
  def change
    create_table :templates do |t|
      t.string  :name,     null: false, limit: 150
      t.text    :description

      t.timestamps
    end
  end
end
```
And with model:
```
class Template < ActiveRecord::Base
  validates_presence_of :name
  validates_length_of :name, maximum: 150
end
```

**Comment by randoum** [comment]
Hi @norman where you able to reproduce?

**Comment by randoum** [comment]
@norman bump
