### ISSUE TITLE
NoMethodError: undefined method `capture_position=' for nil:NilClass

### ISSUE THREAD

**Issue by heaven** [haml/haml#524]
Hi,

I am not actually sure about if this is haml issue or I am doing something wrong.
Basically I have `context` — an controller instance and a block (a part of view). What I am trying to do is to capture the block output, but in separate thread, so:

``` ruby
Thread.new do
  sleep(10)
  out = context.capture(block)
end
```

Raises:

```
ERROR NoMethodError: undefined method `capture_position=' for nil:NilClass
        #    /home/heaven/.rvm/gems/ruby-1.9.3-p0-falcon@crm/gems/haml-3.1.4/lib/haml/helpers.rb:363:in `capture_haml'
```

What I need to do is to release rails app faster, so when a get request comes in I need to respond some data fast and process another part in background.

If I am trying to run `context.capture(block)` in main thread it works as expected.

Thanks in advance,
Alex

**Comment by k0kubun** [comment]
I think https://github.com/haml/haml/issues/524#issuecomment-28069419 is enough. Closing.
