### ISSUE TITLE
Whitespaces and CSS :empty selector

### ISSUE THREAD

**Issue by the8472** [haml/haml#569]
When i do something like

``` haml
%div.message-list
   - @messages.each do |m|
     =m.body
```

Then @messages may be empty and the div will contain a whitespace. Therefore I can't use the CSS :empty selector (which only matches completely-empty elements). Basically I can't use the :empty selector for anything while using haml.

Since haml does not allow content on the same line and indented blocks at the same time i'm forced to add the newline after the div, which in turn causes the whitespace to always be rendered.

Adding conditionals or whitespace eaters seems quite noisy just that i can use a CSS selector on elements.

Maybe constructs like this would work:

``` haml
%div.message-list=@messages.map do |m|
   =m.body
```

Or an option to always munch whitespaces in otherwise empty tags

**Comment by k0kubun** [comment]
Um? I think this can be resolved by following template:

```haml
%div.message-list<
   - @messages.each do |m|
     =m.body
```

Especially in Haml 5.0.0.beta2, it has no pretty mode and no whitespace will appear.
