### ISSUE TITLE
[Enhancement] Define a multi-depth data-* attribute name

### ISSUE THREAD

**Issue by HassenIO** [haml/haml#593]
Hi,
I recently wanted to define an attribute with multi-depth name, something like data-user-name. I tried:

:data => { :user => { :name => "John Doe" } }

but it doesn't work. I have instead to do it like this:

:data => { :"user-name" => "John Doe" }

Why not making the first try the correct way. Pros: We can group data-\* attributes names, like User (for username, age, location,...), Company,... etc.

Here is the stackoverflow ticket about my suggestion: http://stackoverflow.com/questions/12463608/haml-create-data-xxx-yyy-attribute/12463666

Thanks in advance.

**Comment by TheRealNeil** [comment]
Hi, did this ever make it out of beta? I seem to still be having the same situation in version 5.0.0.
`data: { user: { name: "John Doe" } }` generates `data-user="{"name":"John Doe"}"`

**Comment by k0kubun** [comment]
@TheRealNeil I couldn't reproduce the error on Haml 5.0.0. Please write the exact template you are using and how to reproduce the problem.

```html
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ haml -v
Haml 5.0.0
$ cat in.haml
%div{ :data => { :user => { :name => "John Doe" } } }
- d = { :user => { :name => "John Doe" } }
%div{ :data => d } Hi John
$ haml in.haml
<div data-user-name='John Doe'></div>
<div data-user-name='John Doe'>Hi John</div>
```
