### ISSUE TITLE
Haml sets ugly mode in Rails development regardless of a user's initializer settings

### ISSUE THREAD

**Issue by norman** [haml/haml#636]
This problem affects Haml 4.0.0.

In order to set Haml to use `:ugly` mode in development, your initializer must first require `haml/template` because the `:ugly` and `:escape_html` options set by a user will otherwise be overwritten:

``` ruby
require "haml/template"

Haml::Template.options[:ugly] = true
```

This is extremely non-obvious to users and a likely cause of frustration.

We should set up Haml's Railtie in such a way that this file is already loaded by the time the initializers are run.

**Comment by softmonkeyjapan** [comment]
I had a similar problem (reported here http://stackoverflow.com/questions/34804880/weird-behavior-on-form-data-signature-with-a-get-request/34805154). This solved my issue. Thanks
