### ISSUE TITLE
Haml 4.0 doesn't register ActionMailer view handlers

### ISSUE THREAD

**Issue by yangchenyun** [haml/haml#640]
When I upgrade to haml 4.0, email sending **in production** complains
```
ActionView::MissingTemplate: Missing template notify/new_order_user_email with {:locale=>[:"zh-CN"], :formats=>[:html], :handlers=>[:erb, :builder, :arb, :slim]}. 
```

The problem doesn't exist for 3.1.8.

**Comment by norman** [comment]
Closing this issue as stale. If it's still affecting anybody please let me know how to reproduce and we'll look into it.
