### ISSUE TITLE
Sass @import no longer works in inline Haml, regression around (3.2.*)

### ISSUE THREAD

**Issue by brantwedel** [haml/haml#645]
I am experiencing an issue with the Haml inline sass processor handling of `@import` as well I have produced a simple scenario to replicate my results

This is not a duplicate of issue #492 but new behavior documented below

I can confirm that the code below works with `gem "haml", '~> 3.1.4'` as mentioned in #492 up to `gem "haml", '~> 3.1.8'` but **not** with `gem "haml", '~> 3.2.0.alpha.2'` through `gem "haml", '~> 4.0.1.rc.1'`

I often use inline styles in spike code and would like to have my main variables and mixins available via @import so that I can later migrate my code into the appropriate sass files without refactoring, for now I will use Haml (3.1.8) when this is important

_/Gemfile.lock (extract)_

```
rails (3.2.11)
haml (4.0.0)
sass (3.2.6)
sass-rails (3.2.6)
compass (0.12.2)
compass-rails (1.0.3)
```

_/config/initializers/sass/rb_

``` ruby
::Sass::Plugin.options[:load_paths] = Rails.application.config.sass[:load_paths].to_a
::Sass::Plugin.options[:cache] = false
```

_/app/assets/stylesheets/core.sass_

``` sass
$main_color: red
$secondary_color: blue
```

_/app/views/my_models/index.haml_

``` sass
:sass
  @import 'core'
  h1
    color: $main_color
h1 this is text
```

_ruby -v_

```
ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-darwin12.0.0]
```
# HTML Error Output

---
## TypeError in My_models#index

```
Showing /Users/myself/Workspace/myapp/app/views/my_models/index.haml where line # raised:
```

```
can't convert nil into String
```

---

yes the line number is blank in the html error output
# Log Output

```
  Rendered my_models/index.haml within layouts/application (58.3ms)
Completed 500 Internal Server Error in 240ms

ActionView::Template::Error (can't convert nil into String):
  app/controllers/my_models.rb:7:in `index'

  Rendered /Users/myself/.rvm/gems/ruby-1.9.3-p125/gems/actionpack-3.2.11/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.6ms)
  Rendered /Users/myself/.rvm/gems/ruby-1.9.3-p125/gems/actionpack-3.2.11/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.0ms)
  Rendered /Users/myself/.rvm/gems/ruby-1.9.3-p125/gems/actionpack-3.2.11/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (11.8ms)

```

**Comment by ralfebert** [comment]
Patch: https://gist.github.com/ralfebert/37ec9f065cf495e97c67
(Not sure if this is the correct way to fix this - I only looked at the old/new code and made the call to match the new API without deeper understanding of how this code works)

**Comment by jvenezia** [comment]
@scottwb This is not working in production as `::Rails.application.assets` is `nil`.

Do you have any workaround here?

**Comment by k0kubun** [comment]
This problem is approached in https://github.com/haml/haml/pull/868 and https://github.com/haml/haml/commit/5e451f0e29c8511035badc232395cdfaa41d23c8. Please try master branch.
