### ISSUE TITLE
Interpolation and whitespace

### ISSUE THREAD

**Issue by mattwildig** [haml/haml#648]
``` haml
%pre
  Hello #{}
  interpolated
```

produces

``` html
<pre>Hellointerpolated</pre>
```

or

``` html
<pre>Hello interpolated</pre>
```

in ugly mode.

**Comment by hcatlin** [comment]
I agree that this is an issue that should be addressed. And, I further agree that %pre should have absolutely no magic in it. If we want a magic %pre then it should be a filter.

Though, this should be a breaking change in 6.0. Perhaps we need some deprecation warnings in our upcoming release?
