### ISSUE TITLE
Haml 4 does not successfully register an ActionView template handler

### ISSUE THREAD

**Issue by ChristianPeters** [haml/haml#653]
We tried to update our Rails 3.2.13 app to Haml 4.0.0 (via haml-rails 0.4) and got the following problem on a staging server:

```
ActionView::MissingTemplate: Missing template welcome/index, application/index with {:locale=>[:de], :formats=>[:html], :handlers=>[:erb, :builder, :arb, :slim, :coffee, :md]}. Searched in: * "/var/www/compeo/releases/20130319124315/app/views" * "/var/www

Where:
welcome#index
[GEM_ROOT]/gems/actionpack-3.2.13/lib/action_view/path_set.rb, line 58
```

Did I miss any update instructions?

We tried to move 'haml-rails' out of the `:assets` group in the Gemfile, but that did not help.

We do not require 'haml' in our Gemfile and do not have any initializers. Anything missing?

**Comment by lesliev** [comment]
Why does haml-rails not require haml? And why does this break only in production? I'd love if (at least) the behaviour in development and production were the same so that we don't have to have an unexpected debugging session when trying to push an app to production.

**Comment by rosskevin** [comment]
For those that are using rails engines:

Strangely, I just encountered this issue.  We had pruned `haml` from the gemspec of our rails engine, but it was working fine when `RAILS_ENV=test`, which I assume means that some test only dependency was causing it to be included.

I added both `haml` and `haml-rails` back, yet we still don't have a `haml` handler when `RAILS_ENV=development`:

![resolver_rb_-_af_-____projects_af__-_rubymine_2017_2_eap](https://user-images.githubusercontent.com/136564/28094749-01ba68dc-6664-11e7-9f62-aecb7ca024fa.png)

In our main file for our engine lib, I added `require 'haml'` to ensure it was loaded when the engine was, and that solved the problem.

**Comment by krisleech** [comment]
@rosskevin thanks so much. 

I had `require "haml"; require "haml-rails"` in the engines ApplicationController but I could see from the error haml was not registered as a handler.

Adding `require "haml-rails"` or `require 'haml'` to `lib/my_engine/engine.tb` fixed this issue.

The original error was

```
ActionView::Template::Error:
       Missing partial <SNIP>
      :handlers=>[:raw, :erb, :html, :builder, :ruby]
```

Notice no `haml` in `handlers`.

**Comment by ChristianPeters** [comment]
> And why does this break only in production? I'd love if (at least) the behaviour in development and production were the same so that we don't have to have an unexpected debugging session when trying to push an app to production.

I guess because we installed haml on the local system with `gem install haml` at some time.
