### ISSUE TITLE
Using RubyVM::InstructionSequence for compiling haml templates

### ISSUE THREAD

**Issue by Paxa** [haml/haml#674]
Few months ago I found such thing in ruby 1.9 as `RubyVM::InstructionSequence` what allows us to re-run compiled code, it can't save compiled code to string yet (even in ruby 2.0) but it can run compiled code from memory much faster then `Kernel#eval`.

You can see examples and my benchmark here (I got 10x difference) https://gist.github.com/Paxa/321be47319327e5e7058

I hope it will be possible to use for compiling haml templates, is it?

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.
