### ISSUE TITLE
Best way to deal with many attributes or long attribute values?

### ISSUE THREAD

**Issue by Wizek** [haml/haml#677]
We're trying to use Haml and AngularJS together, which creates a problem for us: sometimes we need to use many attributes on a single tag, or long values for some attributes.

## For example:

```
%span.help-inline{ "ng-show" => "form.password.$error.required" }= t.common.form.error.required
```

Ideally, we'd like to write:

```
%span.help-inline{
  "ng-show" => "form.password.$error.required"
}= t.common.form.error.required
```

to ease readability, and reduce need for vertical scrolling even when viewing more than one Haml files side-by-side.

## Another example would be:

```
%input{ :id => "password", :type => "password", :name => "password", "ng-model" => "password", "custom-validators" => "{required:password, strength:enoughStrength(password), charGroup:enoughCharGroups(password), invalid:validChars(password)}" } 
```

The closest we could get was: 

```
%input{ :id => "password",
  :type => "password",
  :name => "password",
  "ng-model" => "password",
  "custom-validators" => "{required:password,
    strength:enoughStrength(password),
    charGroup:enoughCharGroups(password),
    invalid:validChars(password)}" }
```

but then strange `&#x000A;` characters appeared in the value of the "custom-validators" attribute, so we changed a bit back to:

```
%input{ :id => "password",
  :type => "password",
  :name => "password",
  "ng-model" => "password",
  "custom-validators" => "{required:password, strength:enoughStrength(password), charGroup:enoughCharGroups(password), invalid:validChars(password)}" }
```

And the ideal solution would be if Haml let lines continue not just by commas (instead of complaining about "unbalanced brackets"), but by brackets and opening quotation marks as well:

```
%input{
  :id => "password",
  :type => "password",
  :name => "password",
  "ng-model" => "password",
  "custom-validators" => "{
    required:  password,
    strength:  enoughStrength(password),
    charGroup: enoughCharGroups(password),
    invalid:   validChars(password)
  }" }
```

# Solution(?)

Is it possible to do this somehow already?
If not, is there a chance for getting this implemented?

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.
