### ISSUE TITLE
Multiple tags on one line

### ISSUE THREAD

**Issue by bencates** [haml/haml#690]
Jade templates allow you to nest multiple tags on a single line, like so

```jade
ul
  li: a(href:'#') My link
```

which renders to

```html
<ul>
  <li><a href='#'>My link</a></li>
</ul>
```

It can be a pretty big win when working on lists and tables.

I propose importing the same syntax into HAML, making the following snippet compile identically:

```haml
%ul
  %li: %a{href: '#'} My link
```

If anyone else is interested, I'll be happy to write up a pull request this week.

**Comment by mensfeld** [comment]
+1

**Comment by bradherman** [comment]
+1

Tired of doing

    %p
      %b stuff

would love

    %p: %b stuff

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action for us to take. If somebody writes a good pull request for this I'd be happy to consider it.

**Comment by mendelk** [comment]
+1

**Comment by 2metres** [comment]
-1
