### ISSUE TITLE
Cannot modify SafeBuffer in place in template compiler, with XssMods on

### ISSUE THREAD

**Issue by quidquid** [haml/haml#692]
Having an issue with HAML 4.0.3, Ruby 1.9.3-p194, and Rails 3.0.9 wherein I get a "Cannot modify SafeBuffer in place" error on viewing any template. Updated from 3.1.8 which was all good. Here's a call stack:

```
TypeError - Cannot modify SafeBuffer in place:
  activesupport (3.0.9) lib/active_support/core_ext/string/output_safety.rb:127:in `gsub!'
  haml (4.0.3) lib/haml/compiler.rb:452:in `block in build_attributes'
  haml (4.0.3) lib/haml/compiler.rb:428:in `build_attributes'
  haml (4.0.3) lib/haml/compiler.rb:503:in `prerender_tag'
  haml (4.0.3) lib/haml/compiler.rb:177:in `compile_tag'
  haml (4.0.3) lib/haml/compiler.rb:22:in `compile'
  haml (4.0.3) lib/haml/compiler.rb:22:in `block (2 levels) in compile'
  haml (4.0.3) lib/haml/compiler.rb:22:in `block in compile'
  haml (4.0.3) lib/haml/compiler.rb:95:in `compile_root'
  haml (4.0.3) lib/haml/compiler.rb:22:in `compile'
  haml (4.0.3) lib/haml/engine.rb:66:in `initialize'
  haml (4.0.3) lib/haml/template/plugin.rb:25:in `compile'
  haml (4.0.3) lib/haml/template/plugin.rb:30:in `call'
  actionpack (3.0.9) lib/action_view/template.rb:229:in `compile'
  actionpack (3.0.9) lib/action_view/template.rb:134:in `block in render'
  activesupport (3.0.9) lib/active_support/notifications.rb:54:in `instrument'
  actionpack (3.0.9) lib/action_view/template.rb:127:in `render'
```

In the console I'm doing some investigation why compiler.rb would break around 452, and it's because "value" is a SafeBuffer instead of a String at this line:

```
value.gsub!(/&quot;|&#x0022;/, '"')
```

Why is value a SafeBuffer? Because these lines,

```
escaped = Haml::Helpers.html_escape(value.to_s)
value = Haml::Helpers.preserve(escaped)
```

are aliased to html_escape_with_haml_xss and preserve_with_haml_xss in xss_mods.rb. So Compiler gets this html_safe'd string and the gsub! fails to modify it in place. That's a bug, right? Doesn't seem like a way to disable XssMods without forking & editing the source myself. Thanks!

**Comment by benjaminwood** [comment]
A bit late to the party, but I ran into this recently while working on an upgrade. `haml` version was `3.0.25`. Upgrading haml to `3.1.2` resolved it.

**Comment by k0kubun** [comment]
Then, maybe upgrading 3.1.2 to 4.0.3 would break things too, right? 😢

**Comment by benjaminwood** [comment]
I ended up switching to this rails_xss fork and have had better luck: https://github.com/joloudov/rails_xss

There's an issue about it in rails/rails_xss: https://github.com/rails/rails_xss/issues/21

**Comment by k0kubun** [comment]
Thank you for reporting that. I'm not sure but probably the issue was for rails_xss, right? Closing in Haml side.
