### ISSUE TITLE
Rails 4 template digestor compatibility

### ISSUE THREAD

**Issue by nzaillian** [haml/haml#708]
Hi. I've got a couple Rails 4 projects in development right now and for each I've had to include the following in an initializer to have my haml templates properly handled by the ActionView's template digestor (formerly CacheDigests::TemplateDigestor in the Rails 3 cache_digests gem).

```
ActionView::DependencyTracker.register_tracker :haml, ActionView::DependencyTracker::ERBTracker
```

It seems to me that this should be bundled into the initialization of this gem now given that template digests for fragment cache key composition is baked into Rails 4 and doesn't seem to work properly without the above initializer. I would have gone through the usual fork -> pull request flow but I honestly don't know exactly where in the project tree it would be best to have this (or whether you'd like to implement it differently, like by defining a "HamlTracker" though I'm pretty certain that isn't necessary) so thought I should just raise the issue and open it for discussion.

**Comment by jjb** [comment]
as of https://github.com/indirect/haml-rails/pull/51/, haml-rails will automagically do this
