### ISSUE TITLE
HAML for compiling front-end ember.js and Handlebars scripts

### ISSUE THREAD

**Issue by tadruj** [haml/haml#740]
Hi,

front-end community is reinventing the wheel, trying to write HAML inspired tools like emblem.js and haml.js and put them in the front-end side where they don't belong. HAML is a tool to make a developers' job easier and doesn't contribute anything to versatility of the code which runs on the front-end. Handlebars do that part really well.

So HAML code should definitely be precompiled on the developer machine.

There's only one major thing that can not be done using HAML today and that is injecting Handlebar code in the the attributes space of the HTML tags

I solve this problem like this (ember.js example)

```
%hr
<div {{action clickRefresh}}>
%span.glyphicon.glyphicon-refresh
</div>
%hr
```

But it would be really great, if there would be a supported way in HAML to inject arbitrary string into attribute space of HTML tags.

Is it possible to change the HAML spec to support this?

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.
