### ISSUE TITLE
ClojureScript support

### ISSUE THREAD

**Issue by alexherbo2** [haml/haml#754]
[Tilt](https://github.com/rtomayko/tilt) ❯ [Issues](https://github.com/rtomayko/tilt/issues) ❯ ClojureScript support [#230](https://github.com/rtomayko/tilt/issues/230)

**Comment by norman** [comment]
The PR was never merged into Tilt, so for now I'm going to leave this out.

**Comment by judofyr** [comment]
I'll accept a new PR into Tilt now. If anyone have a patch that works on latest Tilt, I'll merge it :-)
