### ISSUE TITLE
Dropping 1.8.7 means version 4.1 should be 5.0

### ISSUE THREAD

**Issue by mattwildig** [haml/haml#761]
Haml 4.1 drops support for 1.8.7. Shouldn’t this be considered a backwards incompatible change according to semantic versioning thus needing a change in the major version from 4 to 5?

**Comment by teeparham** [comment]
:metal:

**Comment by norman** [comment]
@teeparham Given the time that's passed it looks like we can also drop 1.9; planning to do that for 5.0 unless there are any objections.

**Comment by teeparham** [comment]
Dropping 1.9 support for 5.0 is fine with me.

Note to anyone who wants the latest Haml that works with ruby 1.9:

```ruby
gem "haml", "~> 4.1.0.beta"
```

**Comment by hcatlin** [comment]
DROP IT LIKE IT’S HOT.




Pretty much everyone is on 2.0…something these days. At least people who would be actively upgrading a gem!


—
