### ISSUE TITLE
Add escape_html error option.

### ISSUE THREAD

**Issue by kevincox** [haml/haml#781]
It would nice to have an option to make `=` raise an error.  This not only ensures authors thought about whether the value should be escaped but also ensures that your templates will function no matter what the `escape_html` options is.

```ruby
Haml::Engine.new("= 'anything'", escape_html: :error).render
#=> Throws error.
```

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.
