### ISSUE TITLE
RFC: Haml User Tags

### ISSUE THREAD

**Issue by CGamesPlay** [haml/haml#789]
Hi all, I recently wrote a compiler plugin for Haml that enables one to write Haml helpers directly in Haml, and also to call helper functions using Haml syntax (rather than embedded Ruby). I'd love to get some feedback on the idea. The plugin is available on Github as [CGamesPlay/haml_user_tags](http://cgamesplay.github.io/haml_user_tags/).

Features:
- Native Haml syntax for helpers. Instead of `= f.text_field :email, {class: "form-control"}`, you can do `%Input.form-control#email`
- Define new helper methods in Haml templates directly (compare to creating a new partial template file, and then also compare `= render partial: "partials/some_partial", locals: {class: "classes", foo: "bar"}` to `%SomePartial.classes{foo: "bar"}`)

My goal here is to enable reusable, composable components. In particular, please take a look at the [composition](http://cgamesplay.github.io/haml_user_tags/tutorial.html#composition) section of the tutorial.

I'd love to hear feedback on this idea. Thank you!

**Comment by norman** [comment]
I'm frankly embarrassed that I took so long to respond to this. I like this as a plugin, but I think it's outside the scope of what I'd like to offer with Haml itself.  I'd be happy to work on clearing up a better, stable compiler API if necessary to make it easier to maintain a stable extension to Haml like this. @apotonick is going to be working on some similar functionality - see the discussion in #801, if you're still interested in pursuing this your feedback would be welcome.

Once again I'm very sorry to have let this sit so long without so much as a reply.

**Comment by apotonick** [comment]
@CGamesPlay I see your "main API" is `- define_tag :UserTag do |attributes, content|`, that means the `content` is the actual compiled template string?

I want to make capture a low-level language concept in Haml (and every other language on this planet), so this would go hand in hand with your idea.

However, what I don't really understand is: how does a native helper make components simpler? We have to be very careful with this, as native helpers won't work in other languages. Also, a high level of abstraction in views is key to maintainability - have you had a look at Cells, yet, which provides view components on the "Ruby" level? :beers:
