### ISSUE TITLE
stack level too deep if lib/haml/helpers/xss_mods.rb is included twice

### ISSUE THREAD

**Issue by mjrk** [haml/haml#814]
I wanted to add view specs (rspec) for a gem against different sinatra versions. In one of them (sinatra 1.4.2) with padrino-helpers (0.12.4) and haml (4.0.5), it results that the `Haml::Helpers::XssMods` are included twice. Once by lib/haml/template.rb and by lib/padrino/rendering/haml_template.rb. (Note: In sinatra 1.3.0 with padrino 0.10 this did not happen).

The way XssMods#included() aliases the methods of Haml::Helpers, double including results in self-referencing methods and a `stack level too deep`-Error if you call the render method.

I'm not sure, if this can be fixed in Haml. Maybe the included()-method can be made more robust. If not, please tell, if you think padrino 0.12 should be changed. 

Anyway, I open the issue because it took me ages to find out what was actually going on and I hope this issue will help others not to waste time.

**Comment by platzhirsch** [comment]
@mjrk Where would you need to put that workaround?

`config/initializers` doesn't seem to work since the Haml gem gets loaded after the initializer has been executed.

**Comment by mjrk** [comment]
This was in the context of a sinatra testing app. Does this issue exist with haml-rails?

Anyway, you will need to require the haml/template explicitly at some point. Here is the code I used to fix the tests:
https://github.com/amatsuda/kaminari/pull/628/files#diff-bf38db82a9a4af54dcd5b21f791edcabR6

**Comment by k0kubun** [comment]
@mjrk Does this still exist in Haml 5.0.0.beta.2 or master?

**Comment by mjrk** [comment]
@k0kubun yes, the issue still exists.

I tried it in the branch (sinatra_14 tests) with the above workaround with ruby 2.2.6 and `gem 'haml', git: 'git://github.com/haml/haml.git', tag: 'v5.0.0.beta.2'` (had to remove slim though because of no-compatible-versions). With the workaround, the tests run fine.

**Comment by TheSmartnik** [comment]
@konradreiche You can `require 'haml/helpers/xss_mods'` right in initializer file.
It's probably late for you, but someone might find it helpful as an issue still exist in 5.0.4.
