### ISSUE TITLE
Dasherizer Idea

### ISSUE THREAD

**Issue by hcatlin** [haml/haml#818]
Okay, got an idea that I wanted to float. Often times, I end up writing Haml that is mixed with data-attributes and ng-attributes and blah-attributes... and often times it gets very tiresome to write the same freaking attribute prefix.

I propose that we default to "data", with configuration overrides, as an attribute prefix, when the attribute starts with a dash. For instance!

````
    %section{data-type: "article", data-source: "http://www.google.com")
    %section{-type: "article", -source: "http://www.google.com")
````

It would personally save me a lot of repetition. 

Feedback?

**Comment by norman** [comment]
Nobody is going bananas asking for this, and as @mattwildig suggested, you can use `%foo{data: {:bar => 'baz'}}` to get the desired effect without introducting any more syntax. Closing this for now.
