### ISSUE TITLE
issue with capture_haml in presenter

### ISSUE THREAD

**Issue by mathieujobin** [haml/haml#822]
I am trying to use `capture` in a presenter class.
and I am running into an issue with an haml template.
first, I added

``` ruby
include Haml::Helpers
```

so I have access to capture_haml but then I get another error where haml_buffer is nil, but inside the ensure block https://github.com/haml/haml/blob/master/lib/haml/helpers.rb#L390-391

the stacktrace is has follow

```
NoMethodError - undefined method `capture_position=' for nil:NilClass:
  haml (4.1.0.beta.1) lib/haml/helpers.rb:386:in `ensure in capture_haml'
  haml (4.1.0.beta.1) lib/haml/helpers.rb:386:in `capture_haml'
  haml (4.1.0.beta.1) lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
  haml (4.1.0.beta.1) lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
  app/presenters/page_presenter.rb:22:in `page'
```

I made myself a Base Presenter

``` ruby
class RailsPresenter::Base
  include ActionView::Context       # fix output_buffer to be able to capture yielded block
  include Haml::Helpers             # add capture_haml support 
  include Sprockets::Rails::Helper  # add asset pipeline support
  def initialize
    self.debug_assets  = Rails.application.config.assets.debug
    self.digest_assets = Rails.application.config.assets.digest
    self.assets_prefix = Rails.application.config.assets.prefix
    self.assets_environment = Rails.application.assets if Rails.application.config.assets.compile
    self.assets_manifest = Rails.application.assets_manifest
  end

  def t(*args)
    I18n.t(*args)
  end
end
```

and I have a method in my presenter such as...

``` ruby
  def page(&block)
    content_tag(:article, capture(&block).to_s, class: 'content-wrapper')
  end
```

and my view look like this...

``` haml
= page title: 'Annexe', id: 'annexe' do

  %section.block
    %h3= "Déclaration"
...
```

what else am I missing ?

any idea?

thanks

**Comment by zinkkrysty** [comment]
I'm also having issues with calling `capture` from a controller concern. I'm trying to do `view_context.capture` but it seems to break with a NoMethodError: capture_with_haml for my class.

Have you managed to fix this error and if so, how did you do it?

**Comment by mathieujobin** [comment]
oh, it's been a while... i dont quite remember the status, but i believe I did fix it and released it as a gem.

there is a test app inside and some automated testing
feel free to contribute, 

https://github.com/mathieujobin/rails-presenter

**Comment by mathieujobin** [comment]
looks like I am redefining `capture_haml`
https://github.com/mathieujobin/rails-presenter/blob/master/lib/rails_presenter/base.rb

**Comment by k0kubun** [comment]
Closing because it looks resolved.
