### ISSUE TITLE
Attempt to make parser more friendly to extensions

### ISSUE THREAD

**Issue by the-teacher** [haml/haml#823]
Hello! Happy new year!

I want to inform that the current parser is not friendly to extensions. There is my case and I think maintainers should think about it.

I like to use special markers in SLIM or HAML, which makes my view templates better for JS scripting.
I talk about `@` and `@@` markers, which will be compiled into `data-role` and `data-block` attributes

There is real example:

**HAML template**

```haml
%button@btn-action Action

@@home
  Hello World!
  %a#bird(href='#') Tweet
  %a#cat(href='#') Meow
  %a#dog(href='#') Woof
```

it will be compiled in

```html
<button data-role="btn-action">Action</button>

<div data-block="home">
    Hello World!
    <a id="bird" href="#">Tweet</a>
    <a id="cat" href="#">Meow</a>
    <a id="dog" href="#">Woof</a>
</div>
```

And now I can write following JS code ([JQuery extention of selectors](https://github.com/data-role-block/the_data_role_block_jquery/blob/master/app/assets/javascripts/jquery.data-role-block.js))

**JS (CoffeeScript)**
```coffeescript
$ ->
  $('@btn-action').on 'click', (e) ->
    $('@@home a').addClass 'pet'
    false

  $('@@home a').on 'click', (e) ->
    link = $ e.target
    console.log link.text()
    false
```

So. Using `@` and `@@` markers in templates is very pleasure way to write HTML which should be closely related with JS. `data-role` and `data-block` are very popular attributes for JS scripting. Of course is great to have shortcuts `@` and `@@` for them in templates.

So, there is an example, how you can extend your SLIM templates with new markers. 

```ruby
      if defined?(Slim::Parser)
        shortcut    = Slim::Parser.options[:shortcut]
        merge_attrs = Slim::Engine.options[:merge_attrs]

        shortcut.try :[]=, '@',  attr: 'data-role'
        shortcut.try :[]=, '@@', attr: 'data-block'

        merge_attrs.try :[]=, 'data-role',  ' '
        merge_attrs.try :[]=, 'data-block', ' '
      end
```

Looks great, isn't it? And I wrote a little gem for this (https://github.com/data-role-block/the_data_role_block_slim)

**But HAML is not friendly for this**

Now I know only one way to extend my favourite template engine, and it's very painful way.

You can study my variant of this:

**For HAML version < 4.1** -- https://github.com/data-role-block/the_data_role_block_haml_40/blob/master/lib/the_data_role_block_haml_40.rb

**For HAML version >= 4.1.beta1** -- https://github.com/data-role-block/the_data_role_block_haml_41/blob/master/lib/the_data_role_block_haml_41.rb

**Oh! People, it's terrible!** Especially after parser's changes in `4.1.beta1`. Now I have support 2 version of code, to provide desired markers

Can we make HAML parser more friendly to extentions?
Thanks!

**Comment by norman** [comment]
I agree with you. Are you interested in working on this? I would love to see what you have in mind to make it more friendly.

**Comment by the-teacher** [comment]
I think it will be nice to help. I hope, I will find time for this. But I am not sure, that I know how makes it better. I'll try think about it

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.
