### ISSUE TITLE
Insert whitespace with remove_whitespace: true

### ISSUE THREAD

**Issue by Exoth** [haml/haml#824]
Whilst there is a way to remove whitespaces when `remove_whitespace` option is off, I can't find a way to insert a whitespace when `remove_whitespace` is on. It even consumes spaces I add manually. So this makes `remove_whitespace` option unusable in some situations. I think, that it would be great to add some modifiers opposing < and >

**Comment by norman** [comment]
What would be the advantage of having that kind of extreme control over whitespace? Does it outweigh the complexity of a possibly confusing syntax/feature we'd have to build and support, and that users would have to learn how to use? I intuitively doubt it but am open to arguments.

**Comment by Exoth** [comment]
I don't think that this option would be heavily used, but at least it would give a way to do things that are now seem to be impossible to do while `remove_whitespace` is on, like:
I need to have a pair of elements (spans, ruby expressions, anything) separated by ' › '.

    %span
    ›
    %span

renders as `<span></span>›<span></span>`. It didn't add any space, and that is expected behavior. But how can I avoid it? 

    %span
    = ' › '
    %span

renders as `<span></span>›<span></span>` too. Sure I can use &nbsp, but it behaves differently.

Probably I wouldn't even need any additional whitespace modifiers if `remove_whitespace` would remove only whitespaces, generated by HAML itself.

**Comment by graygilmore** [comment]
This comes up quite often for me. I think `remove_whitespace` is great and always have it turned on, but there are some scenarios where I need to annoyingly add `&nbsp;` to get around it. Consider:

```haml
= "One"
- if something
  = "Two"
```

Will result in "OneTwo" unless I add a `&nbsp;` (or similar) to the beginning of "Two". I'd love to be able to do something like this:

```haml
- if something
  *= "Two"
```

...to add a space before. And `=*` to add a space after. Whether or not it's actually `*` doesn't really matter.

**Comment by alex-ball** [comment]
I use HAML in the context of [Twee2](https://github.com/Dan-Q/twee2), which enforces the use of the [`remove_whitespace` option](https://github.com/Dan-Q/twee2/blob/master/lib/twee2/story_file.rb#L15).

This is normally what you want for killing newlines between block level elements, since another processor is involved that converts newlines to `<br>` tags. But it means you can't use natural HAML syntax for situations like this, since the intervening space is removed:

```haml
%p
  %q That's what I think,
  he said.
```

> “That's what I think,”he said.

The only workaround I've found, without resorting to inline HTML, is to use a character reference:

```haml
%p
  %q That's what I think,
  &#32;he said.
```

But some sort of modifier would look cleaner, I think.

**Comment by kevincox** [comment]
Any explanation for why this was closed?

**Comment by hcatlin** [comment]
(Meant to have posted this comment)

Hi-

First of all, thank you for being a Haml-user, and one that cares enough to actually come open an issue. It's for you that we are doing all of this work here!

Unfortunately for this issue (and a bunch that we are mass-closing) we are stopping active development on the 5.x version of Haml (based on the original Regexp that I wrote 15 years ago). Instead, we will be moving to a totally new engine based on @k0kubun's Hamlit engine.

It's almost 2x faster than this implementation!

It's an exciting time for this project, and 6.x might not be fully compatible so we're going to slowly be doing preview releases.

I'm going to be closing this issue, but if it still applies to the new Hamlit-based main branch, we're happy to consider it.

THANK YOU AGAIN FOR CARING! :)

And let's make Haml last another 15 years!
