### ISSUE TITLE
idea: module or snippet that could improve code reuse

### ISSUE THREAD

**Issue by scil** [haml/haml#827]
a feature that's useful  i think .
for example, following is a module or snippet named **box** 
```
.title
    @@@
.body
    @@@
S;
````

haml code that call **box** :
```
@box
    _ this is title
    _ this is content
```

output html code is 
```
<div class="title">
  this is title
</div>
<div class="body">
  this is content
</div>
```

there is an implementator for MtHaml(php)  https://github.com/scil/MtHamlMore .

does this feature valuable ?

**Comment by norman** [comment]
Thanks for the suggestion, we're already working on a similar feature for a future release in #801.
