### ISSUE TITLE
Downcasing of a camelCase html attribute in a link tag?

### ISSUE THREAD

**Issue by reconstructions** [haml/haml#835]
I am using the HAML 4.0.6 in an `edit.html+phone.haml` view (the plus is for Rails new variants feature).  With Rails 4.1.1 and HAML 4.0.6 I am getting the following HTML:

`<a class="back link" data-forceurl="true" href="/songs"></a>`

From this HAML:

%a.back.link{"data-forceUrl" => "true", :href => "#{songs_path}"}

Note the downcased `data-forceUrl` html attribute, which breaks the Framework7 API that I am using.  Any work-around for this?

**Comment by reconstructions** [comment]
I don't think it is a HAML problem.  Even if I use vanilla HTML it comes out downcased in Safari, and is absent altogether in Firefox.

**Comment by norman** [comment]
Yes - it can sometimes be confusing to figure out if behavior is coming from a Rails helper used in your template, or from Haml itself. In this case the Rails helper is definitely the place to look. Closing for now.

**Comment by norman** [comment]
Haml will render this as 

```html
<a class='back link' data-forceUrl='true' href='/'></a>
```

So yes, I think the problem lies elsewhere. Are you checking the inspector or the actual HTML source?

**Comment by mattwildig** [comment]
The [HTML spec says this about `data` attributes](https://html.spec.whatwg.org/multipage//dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes):

> A custom data attribute is an attribute in no namespace whose name starts with the string "data-", has at least one character after the hyphen, is XML-compatible, and contains no uppercase ASCII letters.

When I test this in Chrome the inspector shows the attribute lower-cased, and viewing source directly shows the mixed case.

I don’t know the framework you’re using, but perhaps you need to use hyphenated name in the source: `data-force-url`. You could then access this via the dataset property of the element as `dataUrl`, as hyphens are converted to camel case here – maybe that is what the framework is expecting
