### ISSUE TITLE
Is there a way to capture the raw HAML in a block?

### ISSUE THREAD

**Issue by lifeiscontent** [haml/haml#836]
trying to create a helper for documentation that renders the raw haml syntax via a block

``` haml
= highlight(lang: 'haml') do
  %h1 test
```

then the rendered output would be the raw haml in the block with syntax highlighting.

is this possible?

**Comment by mattwildig** [comment]
I don’t think you can do this solely in the method, but you could use the `:plain` filter:

```haml
= highlight(lang: 'haml') do
  :plain
    %h1 test
```

and then use `capture_haml` in the method:

```ruby
def highlight(opts)
  s = capture_haml { yield }
  # s now contains the raw Haml without the :plain (i.e. "%h1 test" in this example)
  ...
end
```

**Comment by lifeiscontent** [comment]
@mattwildig thanks man, this works well enought :+1:
