### ISSUE TITLE
Outer whitespace removal inconsistency

### ISSUE THREAD

**Issue by eagletmt** [haml/haml#839]
``` haml
%div
  = 'hello'
  %span> world

%div
  hello
  %span> world
```

is rendered as

``` html
<div>hello<span>world</span></div>
<div>
  hello<span>world</span></div>
```

It looks inconsistent to me. I expect both to render the same HTML.
I'm not sure which result is correct.

**Comment by mattwildig** [comment]
I think this is the same as #648. My feeling is they should both behave as the second one (without the script).

**Comment by hcatlin** [comment]
This is the same as #648 and we'll take this as a vote of importance! thanks for the report @eagletmt
