### ISSUE TITLE
Haml Comments: -#   Inconsistent indentation

### ISSUE THREAD

**Issue by dgm** [haml/haml#840]
The documentation says you can:
```
You can also nest text beneath a silent comment. None of this text will be rendered. For example:

%p foo
-#
  This won't be displayed
    Nor will this
                   Nor will this.
%p bar
```

However, when I made a test rails application and put that code in a view, I get:

```
ActionView::Template::Error (Inconsistent indentation: 19 spaces used for indentation, but the rest of the document was indented using 2 spaces.):
    3: -#
    4:   This won't be displayed
    5:     Nor will this
    6:                    Nor will this.
    7: %p bar
    8:
    9:
  app/views/posts/index.html.haml:6
```
The silent comment should not care about indentation, IMHO, since the commented code may not be code or formatted yet.    At any rate, the documentation is incorrect since it yields an error.

**Comment by mattwildig** [comment]
You’re right, this looks like a bug (see also #464). It looks like indents within comments are being ignored _as long as they are a multiple of the document indent_ (usually 2). So in your example if the second line with `Nor will this.` had either one more or one less space (so it was indented 18 or 20 spaces) it would work. I’ll look into it.

**Comment by dgm** [comment]
Whew, I thought I was crazy for a minute.   I had just gotten done showing someone how awesome it was that you could comment out a block so quickly...   and then I try to write some psuedocode under  a comment to help me sort something out and it started throwing errors at me.   :D
