### ISSUE TITLE
Trying to use haml as the handler for email in a ruby gem which is not for use in a Rails app environment

### ISSUE THREAD

**Issue by roscom** [haml/haml#842]
By default haml isn't a default handler, so added it in by:
```
add dependency for haml in gemspec
require 'haml' , 'haml/template' & 'action_view' in the main code.
```
In haml/template.rb it seems that it was designed for use in non Rails apps because it tests for the Rails constant.

Up to the call to haml/template.rb, the Rails constant was undefined. Somewhere in template.rb or it's includes, the constant has been defined meaning that haml won't work in a non Rails environment no matter what.

I haven't been able to pin point where Rails get defined but I'm pretty sure it's not that simple a fix anyway to turn it off or make sure that it doesn't get defined in a non Rails app environment.

I can work around thye problem by brute force commenting out the defined? Rails test in haml/template.rb and all is OK in a non Rails env.

However, I would appreciate it very much to know if I am misguided or have just made a mistake and there is a simple and proper way to incorporate haml in to non Rails apps.

Regards

**Comment by mattwildig** [comment]
How are you trying to use Haml here? If you’re not using Rails you can just use Haml by itself (`require 'haml'`), no need for `haml/template` or `action_view`.

**Comment by roscom** [comment]
I'm using actionmailer inside the gem for non rails use.
```
bundle exec gem list | grep "\(actionmailer\|haml\)"
#=> actionmailer (4.2.1)
#=> haml (4.0.6)

# requires
require 'action_mailer'
require 'action_view'   # <- add
require 'haml'
require 'haml/template'
```
produces the following error
```
.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/haml-4.0.6/lib/haml/template.rb:29:in
 `<top (required)>': undefined method `env' for Rails:Module (NoMethodError)
```
However, using the set up
```
#=> actionmailer (4.1.4)
#=> haml (4.0.6)
```
works just fine. So I was looking for a work around in haml/template for a better test for whether haml is in the Rails environment or not because it would seem 4.2 subverts the test in haml/template.rb

Regards

**Comment by mattwildig** [comment]
I think I’ve tracked this down. Rails 4.2 uses [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer), which [defines the `Rails` module](https://github.com/rails/rails-html-sanitizer/blob/v1.0.2/lib/rails-html-sanitizer.rb#L6) (it is [required in `saintize_helper`](https://github.com/rails/rails/blob/v4.2.1/actionview/lib/action_view/helpers/sanitize_helper.rb#L3), which gets loaded when `ActionView::Base` is referenced, via a sequence of autoloads and explicit requires).

From the Haml side, we can probably just change the test to `defined? Rails.env`, which should resolve this issue for us.

Should this be raised as a Rails (or a rails-html-sanitizer) bug? This code:

```ruby
gem 'actionview', '4.2.1'
require 'action_view'

puts "Before: #{defined?(Rails)}"

ActionView::Base

puts "After: #{defined? Rails}"
```

produces 

```
Before: 
After: constant
```

i.e. simply referencing `ActionView::Base` causes `Rails` to be defined. Does anyone who knows Rails better than me have any thoughts?

**Comment by mattwildig** [comment]
Somewhat related: I think we may need to look at how separating Action View into its own gem affects us. There are a couple of places we check `ActionPack::VERSION` where we probably need to check `ActionView` (or both with a bit of `defined?`).

**Comment by norman** [comment]
@mattwildig Other than in the test helper, we're only checking `ActionPack::VERSION::MAJOR >= 4`, which I think is safe, assuming the various core gems in Rails will always use the same major number as they've done so far. 

Seeing how old Rails 3.2 is at this point, I think we should probably drop support for it in Haml 5.0, in which case we won't have any of these checks anyway.

If we do that, we can backport some of the bugfixes from Haml 5 into Haml 4 and do one or two most releases of the 4.0.x series to support people on older versions of Rails.
