### ISSUE TITLE
Incompatibility haml (4.0.6) -> sprockets (3.0.3) causing error 'wrong number of arguments' for inline :sass filter in haml template

### ISSUE THREAD

**Issue by ralfebert** [haml/haml#844]
I got this error migrating an existing Rails 3.2 project to Rails 4.2:

```
wrong number of arguments (3 for 1)

sprockets (3.0.3) lib/sprockets/context.rb:27:in `initialize'
haml (4.0.6) lib/haml/sass_rails_filter.rb:7:in `new'
haml (4.0.6) lib/haml/sass_rails_filter.rb:7:in `render'
```

HAML's SassRailsTemplate tries to call:

```
scope = ::Rails.application.assets.context_class.new(::Rails.application.assets, "/", "/")
```

But the Sprockets initializer was changed ( https://github.com/rails/sprockets/commit/c192d9f4320074c68786c8c1727c817d2e5c8dca ) to:

```
def initialize(input)
```

It only happens using the inline :sass filter but I could not reproduce this in a separate Rails project, so it's probably triggered only in some cases. https://github.com/haml/haml/issues/645 seems to be a similar but older incompatibility issue.

**Comment by ralfebert** [comment]
Patch: https://gist.github.com/ralfebert/37ec9f065cf495e97c67
(Not sure if this is the correct way to fix this - I just looked at the old/new code and made the calling code to match the new API without deeper understanding of the code)

**Comment by GBH** [comment]
:+1: just spend way too long looking at this

**Comment by jwhitley** [comment]
+1 Just hit exactly this problem in shaking out an app that I've upgraded from Rails 2.3 to 4.2.

**Comment by norman** [comment]
@ralfebert thanks for reporting this. Could you show me your Gemfile for the app affected by this? I'm having a hard time reproducing locally.

**Comment by jwhitley** [comment]
@norman I'm seeing this bug, and just posted [a gist with my Gemfile + Gemfile.lock](https://gist.github.com/jwhitley/4b34a37ccb39b823dfce).

**Comment by aug-riedinger** [comment]
Same issue here with `sprockets (3.4.0)` and `haml (4.0.7)`.

**Comment by ldonnet** [comment]
+1 Just hit exactly this problem in migrating an app from Rails 2.3 to 4.2. Do you plan a fix soon?

**Comment by shuber** [comment]
Running into this problem today as well after bumping sprockets. Looking forward to the fix.

**Comment by longkt90** [comment]
I am running into this problem today  after upgrade sprockets, haml (4.0.7) and sprockets (3.5.2)

**Comment by gucki** [comment]
Same here, works with https://github.com/samphilipd/haml/commit/feb5e88760e2761ab4f4d7fe4354be7cb001bd18

**Comment by jvenezia** [comment]
I had this problem and added this code in an initializer as a workaround:

```ruby
module Haml
  module Filters
    class SassRailsTemplate
      def render(scope=Object.new, locals={}, &block)
        scope = ::Rails.application.assets.context_class.new(
          environment: ::Rails.application.assets,
          filename: '/',
          metadata: {}
        )
        super
      end
    end
  end
end
```

I'm now sure to understand why this is not a good solution (https://github.com/haml/haml/pull/868 still pending). Inline sass is really usefull in our case to provide customs stylesheets very easily, for example:

```haml
- navbar_background_color = current_organization.navbar_background_color

:sass
  .main-navbar
    background: #{navbar_background_color}
```

If inline sass is not supported anymore, I think it should be completely removed to prevent this kind of misunderstanding, or at least clearly explain why it's not recommended in the documentations.

**Comment by NielsKSchjoedt** [comment]
+1 rails 4.2, haml 4.0.7, sprockets 3.2.0

**Comment by waissbluth** [comment]
Has anyone come up with a more definitive solution to this?

**Comment by MechAnizoptera** [comment]
```
 Started GET "/" for 127.0.0.1 at 2017-06-05 22:40:26 -0400
INFO -- : Processing by MainController#index as HTML
INFO -- : Rendering main/index.html.haml within layouts/application
INFO -- : Rendered main/index.html.haml within layouts/application (8.0ms)
INFO -- : Rendered layouts/_assetTags.html.haml (5637.2ms)
INFO -- : Completed 500 Internal Server Error in 5666ms   
FATAL -- : ActionView::Template::Error (wrong number of arguments (1 for 3) for `rgb'):

4:  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
5:  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

F, [2017-06-05T22:40:31.696216 #919] FATAL -- : 
F, [2017-06-05T22:40:31.696273 #919] FATAL -- : (sass):1846
```
Using rails 5.1.1, haml 5.0.1, sass-rails 5.0.6, sass 3.4.24, sprockets-rails 3.2.0

**Comment by k0kubun** [comment]
> FATAL -- : ActionView::Template::Error (wrong number of arguments (1 for 3) for `rgb'):
> F, [2017-06-05T22:40:31.696273 #919] FATAL -- : (sass):1846

rgb is sass's method which Haml doesn't call and it errors in sass view. I don't think it's related to Haml. And there are too few logs to identify the cause. At least we need full error backtrace to solve the problem.
