### ISSUE TITLE
Multiline `if` conditional

### ISSUE THREAD

**Issue by vinagrito** [haml/haml#845]
Assume you have a very long conditional that goes over 100 tabs and breaks your styling. i.e
```
    - if condition_1 && condition_2 && condition_3
      **some code**
```
My first instinct was writing something like:
```
    - if condition_1 && | 
      condition_2 && |
      condition_3
      **some code**
```

But this doesn't work. Is it possible to do something like that?

**Comment by mattwildig** [comment]
All the lines need to have the `|`, including the last one. Your code should work if you add it to the final line of the condition:

```haml
- if condition_1 && | 
  condition_2 && |
  condition_3 |
  **some code**
```

There is possibly a case to be made for making Ruby lines ending in `&&` (and `||)` multiline as well as those ending in `,`. If there really is a lit of independent conditions then even a helper method won’t make it that much neater.

**Comment by vinagrito** [comment]
@mattwildig thx man!
