### ISSUE TITLE
Empty string doesn't render correctly

### ISSUE THREAD

**Issue by andresilveira** [haml/haml#846]
I'm using haml (4.1.0.beta.1) with rails(3.2.x) through the gem haml-rails (0.4).

When rendering this line
```ruby
= button_tag 'All', class: 'btn', data: { status: '' }
```
I get
```html
<button class="btn" data-status name="button" type="submit">All</button>
```
I think the expected behaviour should be, instead:
```html
<button class="btn" data-status='' name="button" type="submit">All</button>
```

I believe this is an issue of Haml code because the same seems to be happening in this port of Haml
https://github.com/creationix/haml-js/issues/63

**Comment by norman** [comment]
The `button_tag` helper is part of Rails, it's behavior isn't controlled at all by Haml.

**Comment by andresilveira** [comment]
Hey @norman I realised that right after having opened this issue, sorry for wasting your time. Besides, querying for `$('.btn'[data-status="")` returned the mentioned DOM.
