### ISSUE TITLE
Change parser into a temple based parser

### ISSUE THREAD

**Issue by kbrock** [haml/haml#851]
Was looking into performance boosts around haml and while comparing to slim, I became aware of [temple](https://github.com/judofyr/temple), the parser behind it. It is quite quick.

It looks to be a pretty good abstraction and there are a number of templating languages written including 2 implementations of haml on temple: [hamlit](https://github.com/k0kubun/hamlit), [faml](https://github.com/eagletmt/faml), which may serve as a reference point in terms of what speedups can be possible.

Not sure if this is possible, or desired, but I saw @norman mention temple in in #848 .

This issue is to pull out the conversation and hear what other people were thinking. Of note, the languages seem to only use data as a hash, which he mentioned in that issue.

**Comment by norman** [comment]
I've been working on this on again and off again for the better part of three years, but have never gotten the time to get something working well enough that I'm willing to share it yet. I would very much like Haml to move to Temple, it's just a matter of somebody getting the time to work on it.

I'm aware of both Hamllit and Faml - they are both interesting projects and I'd even be happy to have one of them eventually become the "official" Haml gem, there are just some incompatibilities that would have to be addressed. And of course the authors would also have to be interested in doing that.

**Comment by teeparham** [comment]
Closing: resolved by #860 and #893.

**Comment by kbrock** [comment]
@teeparham No way!
Congrats on the change. very cool stuff.
