### ISSUE TITLE
Allow additional symbols before argument assigning

### ISSUE THREAD

**Issue by nazar-pc** [haml/haml#853]
Using [Polymer](https://github.com/Polymer/polymer) sometimes I need to write:

``` haml
%my-element(attribute$="some value")
```

But this `$=` is not valid in HAML and there is no way to even escape it, so I'm ending up writing plain HTML in such places, which reduces readability.

Would be nice to allow `$` there (`?` was used in Polymer 0.5 but is not anymore) and/or provide some way to escape symbols so that it would be possible to avoid plain HTML

**Comment by nazar-pc** [comment]
Well, I found workaround:
```haml
%my-element{'attribute$' => "some value"}
```
Similar quotes would be available for consistency in example above, namely:
```haml
%my-element('attribute$'="some value")
```

**Comment by k0kubun** [comment]
Closing because there's a super set: #876. Let's discuss in that issue.
