### ISSUE TITLE
Gem release for 5.0.0.beta

### ISSUE THREAD

**Issue by teeparham** [haml/haml#856]
Can we do a gem release for 5.0.0.beta? I'm running the latest master in production & it works.

There are 150+ commits between 4.1.0.beta.1 and the latest master:

https://github.com/haml/haml/compare/4.1.0.beta.1...master

**Comment by fbernier** [comment]
:+1: I think it's about time.

**Comment by norman** [comment]
Indeed. Will do it this week.

**Comment by mickey** [comment]
:+1: Would love to see this happen as well.

**Comment by annaswims** [comment]
@norman Is there anything I can to to help get another release out?

**Comment by dgilperez** [comment]
@norman any update?

**Comment by phillipoertel** [comment]
Hi all, will there be a 4.1. or 5.0 release any time soon?

**Comment by PikachuEXE** [comment]
It's been a year now
We should have a release for 4.1 at least?

**Comment by fbernier** [comment]
At this point I think everyone should look at https://github.com/k0kubun/hamlit which is a better implementation. Last I used it it noticably sped up the whole website. Thanks to all the haml creators and maintainers!

**Comment by PikachuEXE** [comment]
@fbernier 
I tried that and I got issues after switching to it
And I don't have time to fix those issues since I am working on a large project (large for me anyway)
Also that doesn't conflict with having a released (after > 1 year since last release!)

**Comment by k0kubun** [comment]
:tada: https://rubygems.org/gems/haml/versions/5.0.0.beta.2
