### ISSUE TITLE
compressing :scss output

### ISSUE THREAD

**Issue by josh-m-sharpe** [haml/haml#864]
Is it possible to have Sass compress the output of a :scss: filter?

It doesn't seem to be respecting the fact that I have asset-pipeline compression enabled in rails.

Thanks!

**Comment by k0kubun** [comment]
> Is it possible to have Sass compress the output of a :scss: filter?

No.

> It doesn't seem to be respecting the fact that I have asset-pipeline compression enabled in rails.

That's because :scss filter is not asset. It's html content, different from sccs and shouldn't be compressed. For your use case, you should use separated scss files. Please describe the reason if you really want.

**Comment by k0kubun** [comment]
Or since haml's scss filter is built with tilt, you can do that if tilt is modified for that.
