### ISSUE TITLE
Rendering Haml layout with with block containing ERB produces escaped html string

### ISSUE THREAD

**Issue by ajporterfield** [haml/haml#870]
We're about half way through transitioning an app from ERB to Haml, and I ran into an interesting issue today.  If you call render in an ERB file and pass in a layout (that is Haml) and a block, you get a string of escaped html. Here's an example of what I mean.

view.html.erb

```
<%= render layout: 'layout' do %>
  <b>Hello world!</b>
<% end %>
```

layout.html.haml

```
%p
  = yield
```

You would expect to get a paragraph tag with **Hello world!**, but instead you get `<b>Hello world</b>`.  I tested this in Rails 4.2 and Rails 5, and got the same result.  I also tested this with Slim and got the expected result (unescaped html) and not the escaped html string.  Based on that, my guess is that this issue lies somewhere in this gem.

**Comment by Eosis** [comment]
Unfortunately this issue still persists.

My guess would be an incompatibility with the `CaptureHelper` which you can see [HERE](https://github.com/haml/haml/blob/main/lib/haml/helpers/action_view_mods.rb#L50), where `capture_without_haml` is aliased to the `capture` method defined in the `ActionView` gem.

**Comment by xavierperera** [comment]
Hi @Eosis, the link looks broken, should it point to `original-main` branch? [working link](https://github.com/haml/haml/blob/original-main/lib/haml/helpers/action_view_mods.rb)

**Comment by hcatlin** [comment]
(And sorry, meant to add this comment to the closed links!)

Hi-

First of all, thank you for being a Haml-user, and one that cares enough to actually come open an issue. It's for you that we are doing all of this work here!

Unfortunately for this issue (and a bunch that we are mass-closing) we are stopping active development on the 5.x version of Haml (based on the original Regexp that I wrote 15 years ago). Instead, we will be moving to a totally new engine based on @k0kubun's Hamlit engine.

It's almost 2x faster than this implementation!

It's an exciting time for this project, and 6.x might not be fully compatible so we're going to slowly be doing preview releases.

I'm going to be closing this issue, but if it still applies to the new Hamlit-based main branch, we're happy to consider it.

THANK YOU AGAIN FOR CARING! :)

And let's make Haml last another 15 years!

**Comment by jf** [comment]
for the record, I just came across this exact same issue, and the "fix" (if you can accept the risk): https://haml.info/docs/yardoc/file.REFERENCE.html#unescaping_html. You'll need to trust the source of the HTML
