### ISSUE TITLE
:ruby=

### ISSUE THREAD

**Issue by eiked** [haml/haml#871]
Looks like :suppress_eval ist set to true by default?
(which makes a lot of sense and should not be changed)

I'd like to suggest an enhancement to the filter syntax,
a filter followed by an equal sign should output to haml:

```
:ruby= 'foo'
```

or you might prefer (but this could break existing code)

```
= :ruby
```

Maybe I'm completely wrong on this,
and we should never embed code into views.

But my use case is in formatting table cells data.
That's something like:
    case data
    when BigDecimal then ....
    when Date then ....

and while I could do that with haml dashes,
it would feel much more natural to make that a :ruby section.

I hope my explanation was good enough to understand where I failed.

I believe that this is a shortcoming in the documentation.

It should be clearly written into the documentation on the filters,
that :suppress_eval is set to false (in haml-rails at least, but that's where we are all using haml for)

I'd like to suggest the :rails= syntax (this looks good to me)
(while you might want to opt for =:rails and -:rails)
- rails (4.2.6)
- haml (4.0.7)
- haml-rails (0.9.0)

**Comment by k0kubun** [comment]
What is `:ruby= 'foo'` different from `= 'foo'`? I couldn't understand your motivation.

And `:rails=` and `-:rails` may not be achieved. You can't remove rails context inside template.

**Comment by k0kubun** [comment]
Closing for now since it has no response and the issue description didn't make sense to me.
