### ISSUE TITLE
Funny error after upgrading to security rails patch (Rails.application.assets is nil in haml_assets.rb))

### ISSUE THREAD

**Issue by AntonTrapp** [haml/haml#872]
Updated rails to 4.2.5.2 (bundle update) from 4.2.4, restarted the application, got:

`/config/initializers/haml_assets.rb:1:in`<top (required)>': undefined method `register_engine' for nil:NilClass (NoMethodError)`

haml_assets.rb file looks like this:

`Rails.application.assets.register_engine '.haml', Tilt::HamlTemplate`

Is this a bug or do I have to set the Rails.application.assets somewhere? Completely no idea what is happening here...

Other things changed:

haml -> 4.0.6 -> 4.0.7 (setting it back to 4.0.6 does not change anything)
sprockets -> 3.4.0 -> 3.6.0
tilt -> 2.0.1 -> 2.0.2
many others, if anything else is of interrest I can include it here (or everything)

**Comment by k0kubun** [comment]
Haml doesn't provide `register_engine` method. This is Sprockets issue. Issue this in rails/sprockets if you want.
