### ISSUE TITLE
Context not passed for precompiled template

### ISSUE THREAD

**Issue by duck-rh** [haml/haml#873]
When working on migrating a website from Middleman 3.x to 4.1.x, which is now using HAML 4.x, I encountered a bug while building HAML pages containing markdown, in turn using padrino helpers (included by Middleman). See following trace.

After digging into it I found in the case of interpolation the context is not passed, leading to lib/haml/engine.rb:110 creating a new scope using Object.new, which explains the trace.

This simple patch solves the problem on our side, but maybe this is not the proper way to fix this:
--- haml-4.0.7__orig/lib/haml/filters.rb    2016-04-06 16:37:08.104440580 +0900
+++ haml-4.0.7/lib/haml/filters.rb  2016-04-06 16:48:37.173050910 +0900
@@ -176,7 +176,7 @@
             # too many.
             text = "\n" + text.sub(/\n"\Z/, "\n\"")
             push_script <<RUBY.rstrip, :escape_html => false
-find_and_preserve(#{filter.inspect}.render_with_options(#{text}, _hamlout.options))
+find_and_preserve(#{filter.inspect}.render_with_options(#{text}, _hamlout.options.merge({:context => self})))
 RUBY
             return
           end

You may reproduce the problem using this repo/branch:
  https://gitlab.com/RDO/rdo-website/tree/middleman4

The error trace.
== Request: /install/horizonssl/index.html
       error  build/install/horizonssl/index.html
undefined method `link_to' for #<Object:0x0000000ba986b0>
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/middleman-core-4.1.6/lib/middleman-core/renderers/kramdown.rb:48:in`convert_a'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:70:in `block in inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in`each'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in `inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:86:in`convert_p'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:70:in `block in inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in`each'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in `inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:157:in`convert_li'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:70:in `block in inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in`each'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in `inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:152:in`convert_dl'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:70:in `block in inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in`each'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:69:in `inner'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:332:in`convert_root'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/html.rb:57:in `convert'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/kramdown-1.10.0/lib/kramdown/converter/base.rb:105:in`convert'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/middleman-core-4.1.6/lib/middleman-core/renderers/kramdown.rb:17:in `evaluate'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in`render'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/middleman-core-4.1.6/lib/middleman-core/renderers/haml.rb:56:in `render_with_options'
partials/_footer_custom.haml:10:in`block in render'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/haml-4.0.7/lib/haml/engine.rb:129:in `eval'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/haml-4.0.7/lib/haml/engine.rb:129:in`render'
/home/duck/Projects/Middleman/rdo-website/vendor/bundle/ruby/2.1.0/gems/middleman-core-4.1.6/lib/middleman-core/renderers/haml.rb:35:in `evaluate'
…

**Comment by duck-rh** [comment]
any news?

**Comment by duck-rh** [comment]
Well, one year earlier when I dug into this code I might have had an idea on how to do this, but we ended-up giving up on Middleman 4 so…
Fact is there are several layers of Middleman code to unfold in order to get this minimal test, so that's not really easy as I recall.

**Comment by k0kubun** [comment]
Okay, since your demand to use Middleman 4 is obsoleted, closing for now. Feel free to reopen this if you try it again.
