### ISSUE TITLE
ECMAScript 6 support?

### ISSUE THREAD

**Issue by TangMonk** [haml/haml#874]
There is :javascript and :coffee filter for haml

**Comment by kgrz** [comment]
Hello, you can achieve this by extending the [`Haml::Filters` module](https://github.com/haml/haml/blob/master/lib/haml/filters.rb#L17-L21). The function `register_tilt_filter` wil l let you add any filter that's supported by the [Tilt templating engine](https://github.com/rtomayko/tilt#tilt---)

I've put up a [sample app](https://github.com/kgrz/sinatra-haml-es6) to demonstrate this functionality

**Comment by TangMonk** [comment]
does it support for hamlit?

**Comment by kgrz** [comment]
> does it support 

Not sure what you're referring to, but Hamlit has a slightly different API for adding new custom filters compared to Haml.

**Comment by k0kubun** [comment]
@TangMonk @kgrz Could you try babel-filter branch https://github.com/haml/haml/pull/922? And do you still need it?

**Comment by k0kubun** [comment]
In my personal opinion, babel filter should be in haml-contrib. So continued to https://github.com/haml/haml-contrib/pull/7. Please test it and comment if you want.
