### ISSUE TITLE
Google structured data markup

### ISSUE THREAD

**Issue by shahidbscs** [haml/haml#875]
Hi,
I want to achieve the following, any help will be very appreciated.
<section itemscope itemtype="http://schema.org/Product" class="product-view"

Thanks

**Comment by mattwildig** [comment]
Either:

```haml
%section.product-view{itemscope: true, itemtype: "http://schema.org/Product"}
```

or (using [HTML style attributes](http://haml.info/docs/yardoc/file.REFERENCE.html#htmlstyle_attributes_):

```haml
%section.product-view(itemscope itemtype="http://schema.org/Product")
```

will both produce:

```html
<section class='product-view' itemscope itemtype='http://schema.org/Product'></section>
```
