### ISSUE TITLE
Allow all the characters in new attribute names

### ISSUE THREAD

**Issue by theotherzach** [haml/haml#876]
This issue is a superset of what's mentioned in #853 
## Summary

I want to use Haml with modern JavaScript frameworks. The following does not work. I would like it to work.

``` haml
%button(@keyup.enter="myMethod") A click handler
```

Which forces me to use the old syntax which is a bummer. 

``` haml
%button{ "@keyup.enter" => "myMethod" }` A click handler
```
## Request

Modern JavaScript libraries seem to be in agreement about exactly one thing: crazy characters in attribute names.  Haml supports said characters using the old style hash attributes, but not in the sleek new attribute hash syntax. I would love Haml to allow just about any character as an attribute name other than whitespace, a single closing `)`, or `=`. 
### Polymer
- [ ] `$` - Whatever `$` does in Polymer. (mentioned in #853)
  
  ```
  %my-element(attribute$="some value")
  ```
### Vue
- [x]  `:` - [One way data binding](https://vuejs.org/guide/syntax.html#v-bind-Shorthand) to html attributes
  
  ```
  %a(:href="myData") A link with dynamic href property
  ```
- [x]  `@` - [Event binding](https://vuejs.org/guide/syntax.html#v-on-Shorthand)
  
  ```
  %button(@click="myMethod") A click handler
  ```
- [ ]  `.` - [Event binding with modifiers](https://vuejs.org/guide/syntax.html#Modifiers)
  
  ```
  %button(@keyup.enter="myMethod") A click handler
  ```
### Angular 2
- [ ]  `[]` - [Attribute binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#binding-syntax)
  
  ```
  %a([href]="myData") A link with dynamic href property
  ```
- [ ]  `[]` - [Dynamic Attribute binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#other-bindings)
  
  ```
  %td([attr.colspan]="1 + 1") Creates and binds to the colspan attribute.
  ```
- [ ]  `()` - [Event binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#binding-syntax)
  
  ```
  %button((click)="myMethod") A click handler
  ```
- [ ]  `.` - [Event binding with modifiers](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#binding-syntax)
  
  ```
  %input(type="text"(keyup.enter)="myMethod")
  ```
- [ ]  `[(target)] = "expression"` - [Two way binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#binding-syntax)
  
  ```
  %input(type="text" [(input)]="myModel" placeholder="How is this better than ng-model?")
  ```

**Comment by rowanseymour** [comment]
Keen to hear what direction Haml will take to support this so we can add similar syntax to https://github.com/nyaruka/django-hamlpy. Just allowing characters like `()` in attribute names might cause problems with boolean attributes, e.g. `%span(disabled))`. Maybe better to allow HTML style attribute names to use quotes, e.g. `%span("foo)"="bar")`

**Comment by k0kubun** [comment]
For `@`, partially approached in https://github.com/haml/haml/pull/867.

**Comment by VinSpee** [comment]
also a request for `:`, specifically in css classes for libraries like http://tedconf.github.io/shed-css/ which has classnames like `w:1of3`
