### ISSUE TITLE
View buffer being returned from blocks that return nil

### ISSUE THREAD

**Issue by NGMarmaduke** [haml/haml#877]
Given the following template 

``` haml
%h1 TEST

= if true
  %h2 in block
```

Running the comand

```
haml -t ugly document.haml
```

Expected output:

``` html
<h1>TEST</h1>
<h2>in block</h2>
```

Actual output:

``` html
<h1>TEST</h1>
<h2>in block</h2>
<h1>TEST</h1>
<h2>in block</h2>
```

Possibly related to: https://github.com/haml/haml/issues/694 - which was closed with a PR

**Comment by k0kubun** [comment]
This is an unexpected template. You shouldn't do such nesting because it's not method call with block but just `if` statement and that syntax will bring Haml's internal buffer. For your expected output, you should write:

```haml
%h1 TEST

- if true
  %h2 in block
```

**Comment by NGMarmaduke** [comment]
@k0kubun I understand that your example is correct and expected way of writing that template.  
My point however is there is a behaviour difference between default and uglified outputs. 

`haml document.haml`:
```html
<h1>TEST</h1>
<h2>in block</h2>
```

`haml -t ugly document.haml`:
```html
<h1>TEST</h1>
<h2>in block</h2>
<h1>TEST</h1>
<h2>in block</h2>
```

This results in structurally different HTML being rendered in a production (uglified) environment - which surely should never be the intended behaviour. Either haml should render the same HTML tree regardless of the ugly option or raise an error if the template is unexpected.

**Comment by k0kubun** [comment]
Non-ugly mode is deleted Haml 5. You don't have to care about the difference.

While I think it shoud be SyntaxError, I'm not sure all of such indented cases without "do" are unexpected for now.
