### ISSUE TITLE
Automatically convert -'s (hyphens) in HTML comments to something that doesn't result in an invalid comment

### ISSUE THREAD

**Issue by TylerRick** [haml/haml#88]
If you do

<pre>
/
  this -- is a comment
</pre>

, you end up with an invalid comment (because HTML comments don't allow -- in them), some of which may end up visible on the page.

<pre>

</pre>

What would you think about making `/` automatically "escape" these dangerous characters so that people don't accidentally screw up their page layout?

The `&#45;` entity seems to be a safe alternative:

<pre>
class String
  def safe_in_comment
    gsub('-', '&amp;#45;')
  end
end
</pre>

**Comment by hcatlin** [comment]
While this is something we might entertain, the lack of action on this is making me hit the close button.... 10 years!
