### ISSUE TITLE
data attributes should be renamed according to spec

### ISSUE THREAD

**Issue by gucki** [haml/haml#884]
Take this HAML:

`%div{data: {role: current_role, availableLearningModules: @available_learning_modules}}`

It generates correct HTML like this:
`<div data-role='...' data-availableLearningModules='...'>`

According to this spec https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset the name of `data-availableLearningModules` is converted to all lowercase. To have it accessible by the camelcase name, the generated html would need to be `<div data-role='...' data-available-learning-modules='...'>`.

Imo, it'd be great if haml would automatically convert camelcase data attributes to the required format: replace all uppercase letters with a dash follwed by the lowercase version.

**Comment by k0kubun** [comment]
Why don't you write this as:

```haml
%div{data: {role: current_role, 'available-learning-modules': @available_learning_modules}}
```

IMO, depending on conversion makes template unreadable.

**Comment by k0kubun** [comment]
Closing for now due to inactive response. Opinions for this feature are still welcomed.
