### ISSUE TITLE
Can not parsing "&lt" to "<"

### ISSUE THREAD

**Issue by kunkaiHuang** [haml/haml#889]
hello friends!,in rails haml project.Can not parsing "&lt" to "<",how should i due it? thanks you very much!
`- title "#{@project.name} `
the ` "@project.name" is "<water>" `,and i found the title is "&lt water &gt"

**Comment by k0kubun** [comment]
`title` method doesn't exist in both Rails and Haml by default. It's hard to know what's the problem here.

But it looks like `title` or Haml's interpolation does HTML escaping and it may be fixed by appending `.html_safe` to `@project.name` or `"#{@project.name}`.
