### ISSUE TITLE
may haml some bugs bring on blog format broken, auto add some tab or space

### ISSUE THREAD

**Issue by clay-f** [haml/haml#890]
i did like haml, but occur found some issue

<img width="745" alt="screen shot 2017-01-10 at 08 48 21" src="https://cloud.githubusercontent.com/assets/16079417/21795333/2d5b925c-d73c-11e6-8ef1-d37a833c7fa1.png">

save that would be add some space.

<img width="715" alt="screen shot 2017-01-10 at 08 49 32" src="https://cloud.githubusercontent.com/assets/16079417/21795350/49fa1bea-d73c-11e6-9e14-2bc9d790b478.png">

re-update article, space add again and broken article format.

<img width="1149" alt="screen shot 2017-01-10 at 08 56 23" src="https://cloud.githubusercontent.com/assets/16079417/21795364/672a340c-d73c-11e6-8760-6e77fd1b2778.png">

the logs show:

   `[["text",` "```ruby\r\ndef hello\r\nputs \"hello world!\"\r\nend\r\n```"]

i was used erb re-write for test.

<img width="1169" alt="screen shot 2017-01-10 at 12 07 38" src="https://cloud.githubusercontent.com/assets/16079417/21795428/d1ac05d0-d73c-11e6-9f7b-b2fac9aad3ab.png">

the logs show:

`[["body", "world\r\n\r\nworld\r\n\r\nhello\r\nworld\r\nin\r\nhere\r\n\r\n```ruby\r\ndef hello\r\n puts \"hello world!\"\r\nend\r\n```"], ["updated_at", 2017-01-10 04:07:22 UTC], ["id", 2]]`

may that is show.html.haml issue

**Comment by k0kubun** [comment]
Is this on Rails development? Not sure but Haml 5.0.0.beta.2 may fix this. Please try it.

**Comment by k0kubun** [comment]
Closing for now. Feel free to reopen this if it occurs on Haml 5.0.0.beta.2.
