### ISSUE TITLE
Support for Custom Elements with dash

### ISSUE THREAD

**Issue by shroy** [haml/haml#892]
I would like to build Custom Elements described [in this tutorial](https://developers.google.com/web/fundamentals/getting-started/primers/customelements) in which the name of the element require a dash. 

`%my-component`

Is there currently a way to do this that I am unaware of or a clever work around? If not, any plans to support it?

Thanks.

**Comment by k0kubun** [comment]
Since it's supported, I close this. Please write expected output and actual output if you have any issue.

```
$ gem install haml --pre
$ haml -v
Haml 5.0.0.beta.2
$ cat input.haml
%my-component
%my-component foo
%my-component
  foo
$ haml input.haml
<my-component></my-component>
<my-component>foo</my-component>
<my-component>
foo
</my-component>
```
