### ISSUE TITLE
Ruby 2.4.0 bug 12782

### ISSUE THREAD

**Issue by yb66** [haml/haml#909]
Cross posting [Tilt issue #311](https://github.com/rtomayko/tilt/issues/311) as it's relevant here too (unless you say otherwise) 

Hi,

I've just upgraded to Ruby v2.4.0 and appear to have been bitten by the bug described on the Ruby bug tracker.

    myproj/vendor/ruby/2.4.0/gems/tilt-2.0.6/lib/tilt/haml.rb:50:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /opt/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Haml::TempleEngine#precompiled_method_return_value

They appear to have decided to revert the change that caused it, but to add warnings, probably to nudge people to stop forwarding to private methods. I thought I'd be helpful and open this issue ahead of time. Or for it to be fixed immediately (no pressure;)

Regards,
iain

ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin13]
Tilt v2.0.6
Haml v4.0.7 and 5.0.0.beta.2

**Comment by k0kubun** [comment]
We have API exactly for this problem https://github.com/haml/haml/pull/896.

I'll use it for Haml 5 and fix it in another way in Haml 4, considering Haml 4 is already in stable branch.

**Comment by k0kubun** [comment]
Fixed this in stable branch https://github.com/haml/haml/commit/ac290b53d00158ebf031166459e20fa305c1113d. Please wait for new 4.0.x release.

And for Haml 5, I opened https://github.com/rtomayko/tilt/pull/312. Since there's nothing to do in Haml side, closing this issue.

**Comment by yb66** [comment]
Thanks, much appreciated.

**Comment by ireneybean** [comment]
> Fixed this in stable branch [ac290b5](https://github.com/haml/haml/commit/ac290b53d00158ebf031166459e20fa305c1113d). Please wait for new 4.0.x release.
> 
It seems like there has never been another 4.0.x release? Or am I missing something? (I would like to move to 5 but have not been able to yet because it breaks my app  #770 )

**Comment by x-yuri** [comment]
@k0kubun https://github.com/haml/haml/commit/ac290b53d00158ebf031166459e20fa305c1113d was deleted. Any other suggestions? Can it be resurrected by any chance?

@ireneybean Did you manage to migrate to haml 5.x? Does `options.escape_filter_interpolations` help in this regard?

**Comment by ireneybean** [comment]
@x-yuri Yes! We're currently running with haml-5.1.2 and using `options.escape_filter_interpolations` set to false with no problems.

**Comment by k0kubun** [comment]
> @k0kubun ac290b5 was deleted. 

I don't get what you mean. Did you read the message of the commit? Haml 5.x and some newer versions of Tilt should work. Consider upgrading your Tilt.

**Comment by hcatlin** [comment]
We don't support Haml 4 as it was released over 4 years ago. We will continue to support Haml 5 until Haml 6 is fully released.

Sorry!

**Comment by x-yuri** [comment]
> Did you read the message of the commit?

Yes, what about it? WIll upgrading `tilt` let me stay with `haml 4.x`?

> We don't support Haml 4 as it was released over 4 years ago.

It's not about support. Supposedly the `stable` branch was deleted, which had some useful commits. I was able to [restore][a] it though.

I'm not a developer, not in this case. And upgrading the major version not knowing the code... I'd prefer the developer to handle it. Hopefully with the feedback from ireneybean that would be easy.

[a]: https://github.com/x-yuri/haml/
