### ISSUE TITLE
Alternative to ugly option

### ISSUE THREAD

**Issue by andrewkendall** [haml/haml#923]
I see from a recent commit that the option `Haml::Template.options[:ugly] = false` has been removed. Is there another way to activate the automatic code formatting that this option used to produce?

**Comment by k0kubun** [comment]
Unfortunately, no. Its support is just dropped since Haml 5.

You can see the reasons here: https://github.com/haml/haml/pull/894

**Comment by k0kubun** [comment]
I still want some use case for `ugly: false`. If you have some problem in Haml 5, I have some ideas which aren't Haml 4 way.

**Comment by andrewkendall** [comment]
Thank you @k0kubun. I feared as much as I know that many people didn't like the option. It's a real shame as I have some specific use cases where it's incredibly useful, but I understand it's removal if most people weren't using it. I'll try and look for some alternatives.

**Comment by andrewkendall** [comment]
@k0kubun if you'd like me to run through my use case let me know.

**Comment by k0kubun** [comment]
Your use case is very welcome. Please tell me.

What I think is that having a filter that indents HTML automatically *AFTER* HTML is generated by `ugly: true` is still acceptable in Haml 5. The reason we removed it was indenting *DURING* HTML is generated in Haml compiling was too hard to maintain.

**Comment by andrewkendall** [comment]
That makes sense, it's only the end output to users that is important and only in one app so after would be perfect. I work on several apps that use Haml and in most cases we have switched to Hamlit where formatting wasn't needed (many thanks for your great work on Hamlit by the way!). I'll put together full details on how we're using ugly shortly and let you know.

**Comment by k0kubun** [comment]
Note that indenting after generating HTML will change spacing on browser since it puts extra spaces for indentation. Of course, in some cases, such problem also existed between `ugly: true` and `ugly: false` in Haml 4. That's why we thought it's nonsense and removed.

So writing use case considering such background (spacing breakage problem) would be appreciated.
