### ISSUE TITLE
Filter docs are broken

### ISSUE THREAD

**Issue by Kapeli** [haml/haml#928]
If you go to http://haml.info/docs/yardoc/file.REFERENCE.html#filters and scroll to/search for "cdata-filter" you'll see that the docs aren't generated properly.

**Comment by danielstrimpel** [comment]
Can you be more specific about what's wrong with the docs?

**Comment by Kapeli** [comment]
The markdown for the filter docs doesn't seem to get parsed correctly

Screenshot:

 ![screen shot 2017-05-15 at 20 25 17](https://cloud.githubusercontent.com/assets/1445635/26070255/a0c4f800-39ac-11e7-9230-22d60a75718d.png)

**Comment by dnamsons** [comment]
@k0kubun Looks like this is fixed 
<img width="1147" alt="screenshot 2018-11-12 at 19 02 24" src="https://user-images.githubusercontent.com/24278257/48363005-9054b000-e6ad-11e8-8a31-469dc7ac685f.png">

**Comment by teeparham** [comment]
This appears to be fixed. 

The bottom of the page says `Generated on Wed Oct 3 20:56:01 2018 by yard 0.9.16 (ruby-2.6.0).`
