### ISSUE TITLE
Incorrect class ordering. 

### ISSUE THREAD

**Issue by HooFoo** [haml/haml#932]
I have a problem with a class order. My frontend developer made this construction.
`%input#auth_login.f_input.input_v1.checkEmpty{:class => 'validate[required, custom[email]]', :name => "login"}`
and he expected
`<input class="checkEmpty f_input input_v1 validate[required, custom[email]] _empty" id="auth_login" name="login">`
but got
`<input class="checkEmpty custom[email]] f_input input_v1 validate[required, _empty" id="auth_login" name="login">`
Option for disable feature of class ordering required.

**Comment by k0kubun** [comment]
Duplicated with https://github.com/haml/haml/issues/306.

Please wait https://github.com/haml/haml/pull/882 to be added.
