### ISSUE TITLE
Haml::TempleEngine: Option :outvar is invalid

### ISSUE THREAD

**Issue by grasp** [haml/haml#935]
how we stop this print ?

Haml::TempleEngine: Option :outvar is invalid

**Comment by joshuamcginnis** [comment]
I'm experiencing the same.

```
Haml::TempleEngine: Option :outvar is invalid
~/.rvm/gems/ruby-2.4.1/gems/tilt-2.0.7/lib/tilt/haml.rb:50:in `block in precompiled_postamble':
Haml::Engine#precompiled_method_return_value at ~/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157
forwarding to private method Haml::TempleEngine#precompiled_method_return_value  
```

gem 'sinatra', '~> 2.0'
gem 'haml'

**Comment by k0kubun** [comment]
This is basically Sinatra and Tilt's problem. Closing in favor of https://github.com/rtomayko/tilt/issues/316.Please wait https://github.com/rtomayko/tilt/pull/317 to be released.
