### ISSUE TITLE
uninitialized constant Sass::Script::String

### ISSUE THREAD

**Issue by joelim01** [haml/haml#937]
Hello,
Getting the following when compiling assets in my rails 4 app:
`SassC::SyntaxError - Error: error in C function image-url: uninitialized constant Sass::Script::String`

It is being thrown when Rails reaches the following line in a .scss file:
background-image: image-url("images/image.png");

Here's a bit of the backtrace:

```
sassc () lib/sassc/engine.rb:47:in 'render'
sassc-rails () lib/sassc/rails/template.rb:34:in 'block in call'
sprockets () lib/sprockets/utils.rb:167:in 'module_include'
sassc-rails () lib/sassc/rails/template.rb:33:in 'call'
sprockets () lib/sprockets/sass_processor.rb:30:in 'call'
sprockets () lib/sprockets/processor_utils.rb:75:in 'call_processor'
```

Compiling the same scss file in a fresh 'test-app' using the same version of the sassc, sassc-rails, sprockets, sass, and jquery-fileupload-rails gems is successful. Once I add in the HAML gem, however, the error appears.

Changing the HAML gem version from 3.1.8 to 4.0.7 resolves the issue but this may not be possible due to dependencies in the original app. 

It is also worth mentioning that removing the jquery-fileupload-rails gem from the project stops the error when compiling the scss even with the HAML 3.1.7 gem.

If you have any suggestions for where I might begin to look to resolve the conflict, I would appreciate the help.

Thanks

**Comment by k0kubun** [comment]
Did you try Haml 5.0.1? 

As you can see from https://github.com/haml/haml/blob/master/CHANGELOG.md#500, at least Sprockets >= 3 is NOT supported by Haml <= 4. Though I'm not sure it's related.

**Comment by k0kubun** [comment]
Closing due to no response and sounds already solved in v5.
