### ISSUE TITLE
haml_tag should respect :/ for any format

### ISSUE THREAD

**Issue by gkellogg** [haml/haml#939]
In [haml_tag](https://github.com/haml/haml/blob/master/lib/haml/helpers.rb#L508), the test for creating a self-closing tag is dependent on `options[:format] == :xhtml`. In fact, these are completely different considerations. Self-closing tags are legitimate for any HTML variant, and generally considered good practice. (In my case, I also use Haml for generating pure XML, not just XHTML).

In [Start tags](https://www.w3.org/TR/html5/syntax.html#start-tags) in the HTML5 spec, point 6 says the following:

> Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single "/" (U+002F) character. This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

This should make it clear that, regardless of variation, a void element may end with a "/".

In any case, if `haml_tag` is specifically invoked with the `:/` flag, then it should be honored.

**Comment by abrisse** [comment]
+1, we need them for XML format
