### ISSUE TITLE
Haml::OptionsTest#test_buffer_defaults_values_are_the_same_as_rails_defaults is unstable

### ISSUE THREAD

**Issue by voxik** [haml/haml#943]
There seems to be some race condition in test suite, since the following test fails from time to time:

~~~
  1) Failure:
Haml::OptionsTest#test_buffer_defaults_values_are_the_same_as_rails_defaults [/builddir/build/BUILD/haml-5.0.1/usr/share/gems/gems/haml-5.0.1/test/options_test.rb:15]:
key: escape_html.
Expected: true
  Actual: false
~~~

**Comment by k0kubun** [comment]
off topic: As it's not executed in concurrent way, actually it's not race condition but load order issue.

It's known issue and solved in `rake test` task. How do you run tests? See around https://github.com/haml/haml/blob/d4d36359004e28c0e475184cc6e64c5801b62747/Rakefile#L7-L20.

**Comment by voxik** [comment]
Ah, thx for explanation and sorry for the noise. I'll adjust Fedora package appropriately. So far, it's been using following command to execute the test suite:

~~~
ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
~~~
