### ISSUE TITLE
ActionView::Template::Error (Unsupported callback code)

### ISSUE THREAD

**Issue by seanhandley** [haml/haml#944]
I've updated HAML to 5.0.1 as part of ongoing work to port our Rails app from 5.0.2 to 5.1.2 (previous HAML version was 4.0.7).

I was seeing a deprecation warning regarding Erubis/Erubi, hence upgrading HAML:

```
DEPRECATION WARNING: ActionView::Template::Handlers::Erubis is deprecated and will be removed from Rails 5.2. Switch to ActionView::Template::Handlers::ERB::Erubi instead. (called from <top (required)> at /Users/sean/src/datacentred/stronghold/config/application.rb:7)
```

Now I'm met with this strange error when I try to log into our app:

```
Started GET "/sign_in?next=%2F" for ::1 at 2017-07-26 15:39:46 +0100
   (0.3ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.3ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Processing by SessionsController#new as HTML
  Parameters: {"next"=>"/"}
  Rendering sessions/new.html.haml within layouts/customer-sign-up
  Rendered sessions/new.html.haml within layouts/customer-sign-up (10.0ms)
Completed 500 Internal Server Error in 29ms (ActiveRecord: 0.0ms)



ActionView::Template::Error (Unsupported callback code):
```

Here is the contents of `sessions.new.html.haml`:

```haml
- title "Sign In"

%h3 Sign In

= display_flash

= form_for(User.new, :url => sessions_path, :method => :post, :html => {:role => 'form'}) do |f|
  = hidden_field_tag :next, params[:next]
  .form-group
    = f.email_field :email, :class => "form-control",
                    :id => "inputEmail", :placeholder => "Email address", :autofocus => ''
  .form-group
    = f.password_field :password, :class => "form-control wink-password",
                       :id => "inputPassword", :placeholder => "Password"
  = f.submit 'Sign In', :class => 'btn btn-primary', style: 'width: 100%; margin-bottom: 10px'
  .pull-right
    = link_to 'Reset Password', new_reset_path
    |
    = link_to 'Create Account', create_signup_path
  %p= link_to 'Trouble logging in?', ExternalLinks.cookie_documentation_path

```

If I change the contents of the template `new.html.haml` to the text "Hello" then I get this error:

```
ActionView::Template::Error (Unsupported callback static)
```

I've spent a few hours trying to find anything helpful online regarding this, but so far I've seen nothing.

Any clues what may be going on here?

**Comment by k0kubun** [comment]
We can't help without error backtrace. We even don't have which line is wrong in your template. Set logl_level = debug first if you don't, then please put full log of the failed request.

And if you can't create error backtrace, please create reproductive repository.

**Comment by seanhandley** [comment]
The log level is already set at debug. I haven't edited that backtrace at all so it's odd that there's clearly lines missing from it.

**Comment by k0kubun** [comment]
I see. Then we need reproductive environment to help you.

**Comment by seanhandley** [comment]
I've tried to make one. By the time I pull all our production code out of it, the problem disappears.

I suppose it could be a combination of conflicting gems? I'll share our Gemfile:

```ruby
source 'https://rubygems.org'

gem 'rails', '5.1.2'
gem 'mysql2', '~> 0.3'
gem 'sdoc', '~> 0.4.0',  group: :doc
gem 'bcrypt', '~> 3.1'
gem 'unicorn', '~> 5.0'
gem 'haml', '~> 4.0'
gem 'cancancan', '~> 1.15'
gem 'fog-openstack', '~> 0.1'
gem 'gravatar_image_tag', '~> 1.2.0'
gem 'js-routes', '~> 1.2'
gem 'sidekiq', '~> 4.0'
gem 'database_cleaner', '~> 1.6'
gem "audited", "~> 4.5"
gem "rails-observers", git: 'https://github.com/rails/rails-observers'
gem 'verbs', '~> 2.1.4'
gem 'faraday', '~> 0.9'
gem 'redcarpet', '~> 3.3'
gem 'async-rails', '~> 1.5'
gem 'honeybadger', '~> 2.3'
gem 'sirportly', '~> 1.3'
gem 'kaminari', '~> 0.16'
gem 'bootstrap-kaminari-views', '~> 0.0.5'
gem 'dalli', '~> 2.7'
gem 'clockwork', '~> 1.2'
gem 'clockwork_web', '~> 0.0.5'
gem 'aws-s3', git: 'https://github.com/datacentred/aws-s3.git'
gem 'sinatra', git: 'https://github.com/sinatra/sinatra'
gem 'responders', '~> 2.0'
gem 'restforce', '~> 2.1'
gem 'starburst', '~> 1.0'
gem 'country_select', '~> 2.2'
gem 'countries'
gem "recaptcha", :require => "recaptcha/rails"
gem 'tel_to_helper'
gem 'rest-client', '~> 1.8'
gem 'geo_ip', '~> 0.6'
gem 'world-flags', '~> 0.6'
gem 'nokogiri', '~> 1.7.1'
gem 'premailer-rails', '~> 1.9'
gem "slack-notifier", '~> 1.2'
gem "maxmind", '~> 0.4'
gem "deep_merge", '~> 1.0'
gem 'stripe-rails', '~> 0.3'
gem 'holidays', '~> 2.2'
gem 'minitest-ci', :git => 'git@github.com:circleci/minitest-ci.git'
gem "useragent"
gem 'soulheart'
gem 'hiredis', '~> 0.6.0' # Skip using JRuby
gem 'redis', '>= 3.2.0', require: ['redis', 'redis/connection/hiredis']
gem 'redis-namespace'
gem 'statesman', '~> 2.0'
gem 'parallel'
gem 'docker-api', '~> 1.31'
gem 'gibberish', '~> 2.1'
gem 'paranoia', '~> 2.3'
gem 'harbour', git: 'git@github.com:datacentred/harbour.git', branch: 'master'

group :test, :acceptance do
  gem 'faker'
  gem 'machinist'
  gem 'minitest', '~> 5.10', '!= 5.10.2'
  gem "minitest-rails"
  gem "minitest-rails-capybara"
  gem 'poltergeist'
  gem 'rails-controller-testing'
  gem 'simplecov'
  gem 'timecop'
  gem 'launchy'
end

group :test do
  gem 'webmock'
  gem 'vcr', '2.9.3'
end

# Assets gems
gem "select2-rails", '~> 3.5.9.1'
gem 'bootstrap-sass', '~> 3.3.7'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'sprockets', '~> 3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 2.7'
gem 'coffee-rails', '~> 4.1'
gem 'therubyracer', '~> 0.12.2', platforms: :ruby
gem 'momentjs-rails', '~> 2.8.3'
gem 'font-awesome-sass', '~> 4.5'


source 'https://rails-assets.org' do
  gem 'rails-assets-angular', '~> 1.4'
  gem 'rails-assets-angular-resource', '~> 1.2'
  gem 'rails-assets-angular-bootstrap', '~> 0.11'
  gem 'rails-assets-angular-sanitize', '~> 1.2'
  gem 'rails-assets-angular-gravatar', '~> 0.2'
  gem 'rails-assets-angular-animate', '~> 1.2'
  gem 'rails-assets-angular-md5', '~> 0.1'
  gem 'rails-assets-chained', '~> 1.0'
  gem 'rails-assets-bootstrap-select', '~> 1.7'
  gem 'rails-assets-hideShowPassword', '~> 2.0'
  gem 'rails-assets-normalize-css', '~> 3.0'
  gem 'rails-assets-clipboard', '~> 1.5'
  gem 'rails-assets-bootstrap-toggle'
  gem 'rails-assets-highcharts'
  gem 'rails-assets-jquery.terminal', '~> 0.10'
  gem 'rails-assets-angular-inview', '~> 2.2'
  gem 'rails-assets-angular-file-upload'
end

group :development do
  gem 'puma'
  gem 'i18n_yaml_sorter', '~> 0.2.0'
  gem 'capistrano',  '~> 3.1'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'net-ssh', '~> 2.8.0'
  gem 'spring', '~> 1.1.3'
  gem 'web-console', '~> 3.0'
end

group :development, :test do
  gem 'traceroute'
  gem 'brakeman', :require => false
  gem 'rack-mini-profiler', :require => false
  gem 'bullet'
  gem 'rubycritic'
  gem 'bundler-audit'
  gem 'rspec_junit_formatter', '0.2.2'
end

group :production, :staging do
  gem 'newrelic_rpm', '~> 3.9'
  gem 'unicorn-worker-killer', '~> 0.4.4'
  gem 'rack-attack'
end
```

**Comment by k0kubun** [comment]
Only Gemfile can't reproduce a problem. I'm waiting for "reproductive repository with minimum requirements". Do you think really all these gems are necessary to reproduce it?

**Comment by seanhandley** [comment]
I appreciate that @k0kubun but I'm working on a commercial project and I can't share the code.

I've tried to reproduce the issue in a new repository and I had no luck - I just can't get it to reproduce. I will continue attempting to debug it in our codebase and post an update here if I discover the root cause. Or perhaps others will find this issue if they see similar problems elsewhere.

In the meantime, I guess there's nothing to do but close this issue for now.

**Comment by staycreativedesign** [comment]
I've had the same problem... will try to replicate..

**Comment by k0kubun** [comment]
Possibly it's the same as https://github.com/haml/haml/issues/946. Please try to use master branch.

**Comment by staycreativedesign** [comment]
Reproduced error

[https://github.com/staycreativedesign/haml_errors](https://github.com/staycreativedesign/haml_errors)

**Comment by k0kubun** [comment]
It raises SyntaxError and your error is not related to this issue, right?

**Comment by k0kubun** [comment]
Like this:

```
SyntaxError (/Users/kokubun/src/github.com/staycreativedesign/haml_errors/app/views/invoices/index.haml:5: syntax error, unexpected keyword_ensure, expecting keyword_end
...:Util.html_safe(_erbout);ensure;@haml_buffer = @haml_buffer....
...                               ^
/Users/kokubun/src/github.com/staycreativedesign/haml_errors/app/views/invoices/index.haml:8: syntax error, unexpected end-of-input, expecting keyword_end):

```

**Comment by k0kubun** [comment]
It seems that Haml compiler bug with empty each loop

**Comment by staycreativedesign** [comment]
Correct... :) sorry its not the same bug?

**Comment by k0kubun** [comment]
Yeah, anyway reproductive repository was very helpful to identify it. Thanks :)

Filed: https://github.com/haml/haml/issues/954

**Comment by aledustet** [comment]
I am having this same issue, this is the stack trace I'm seeing

`
gems/clockwork-2.0.2/lib/clockwork/manager.rb:44:in `on'
gems/clockwork-2.0.2/lib/clockwork.rb:38:in `on'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:86:in `dispatcher'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:49:in `compile'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:7:in `each'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:82:in `dispatcher'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:49:in `compile'
gems/temple-0.8.0/lib/temple/mixins/dispatcher.rb:45:in `call'
gems/temple-0.8.0/lib/temple/engine.rb:50:in `block in call'
gems/temple-0.8.0/lib/temple/engine.rb:50:in `each'
gems/temple-0.8.0/lib/temple/engine.rb:50:in `inject'
gems/temple-0.8.0/lib/temple/engine.rb:50:in `call'
gems/haml-5.0.4/lib/haml/temple_engine.rb:41:in `compile'
gems/haml-5.0.4/lib/haml/engine.rb:61:in `initialize'
`

**Comment by k0kubun** [comment]
Thanks for the backtrace. It was much helpful than the original report.

And it seems that it's raised in clockwork.gem. https://github.com/Rykian/clockwork/blob/master/lib/clockwork/manager.rb#L44

Also, if Clockwork is included on the top-level, it seems to break temple.gem's behavior. I think both clockwork and temple can do better, and at least the place to report the issue is not here (haml repository) because it should happen on slim too.

**Comment by aledustet** [comment]
Thanks @k0kubun i opened tickets on temple and clockwork

https://github.com/judofyr/temple/issues/118
https://github.com/Rykian/clockwork/issues/39

In case anybody wants to follow up

**Comment by aledustet** [comment]
The issue was that the **clock.rb** files content was not 'namespaced':

```ruby
include Clockwork
every(1.hour, ...
...
```
After moving it under the module the problem was solved:
```ruby
module Clockwork
  every(1.hour, ...
end
```
I closed the issues on temple and clockwork 👍
