### ISSUE TITLE
[Improvement] Add a PHP filter.

### ISSUE THREAD

**Issue by ycrepeau** [haml/haml#949]
I use haml (the ruby version) in a gulp project. The .haml files should be translated to a .php file and should support a :php filter.

The good new is that I have patched haml locally. The bad news is that each time I update haml, I have to find the new installation and re-apply the patch.

I will fix this once for all. I will clone the project and submit a pull request with the patch I have used for years now. It is just 6 lines of code. 

Once operational, the :php filter will work like this:

```php
-# coding: utf-8

:php
    /*
     * Template Name: adminSite
     *
     * @author: Yanik Crépeau <ycrepeau@me.com>
     */

    global $lln;
    require_once($_SERVER['DOCUMENT_ROOT']."/wordpress/wp-load.php");
    include_once("i18n.php");
    include_once("db.php");

    $mysite_id = NULL;
    $submit         = $_POST['submit'];
    if (!current_user_can('edit_pages')) die("Privilèges auteur");

    $mysite_id      = $_GET['site_id'];
    //error_log("Line 19, mysite_id: $mysite_id");
    //...

#remaining of haml code goes here
```

**Comment by mattwildig** [comment]
This has already been implemented in haml-contrib: https://github.com/haml/haml-contrib/blob/master/lib/haml/filters/php.rb

You just need to `require 'haml/filters/php'` (after installing the `haml-contrib` gem) and you can use this filter exactly as you want.

**Comment by ycrepeau** [comment]
How should I handle this in a gulp environment? 

```require 'haml/filters/php'``` smells like ruby.  Gulp is a node.js environment.

At this time my gulpfile.coffee looks like:

```coffee
# Create the .php files from the .haml
gulp.task 'haml', ->

  # Site local (MAMP)
    gulp.src './haml/*.haml'
        .pipe haml (  {doubleQuote: true} )
    .pipe replace "&lt;", "<"
    .pipe replace "&gt;", ">"
    .pipe dest '', {ext: '.php'}
    .pipe gulp.dest '../'
```

Where should I add the ```require 'haml/filters/php'``` in that context?

**Comment by mattwildig** [comment]
Assuming you’re using https://www.npmjs.com/package/gulp-ruby-haml, it looks like you should be able to do something like:

    .pipe haml (  {doubleQuote: true, require: ["haml/filters/php"]} )

**Comment by ycrepeau** [comment]
Thank you.
