### ISSUE TITLE
Add support for foreign characters (e.g. german umlauts)

### ISSUE THREAD

**Issue by farbexot** [haml/haml#953]
Hi. Would be great if haml let me compile projects that use utf-8 characters such as german umlauts (ä, ö, ü) or áccents etc...

**Comment by k0kubun** [comment]
Please write expected template to compile. I understand it's compilable.

```rb
Haml::Engine.new("ä").render
# => "ä\n"
```

**Comment by farbexot** [comment]
I'm using the latest version 5.0.2 and compile haml files using Terminal on OSX.
If I create a simple .haml file only containing 

`%p ä`

I'll get the error: _Haml error on line 57: Invalid US-ASCII character "\xC3"_

**Comment by k0kubun** [comment]
Still few information to reproduce the problem. 

```
$ haml -v
Haml 5.0.2
$ cat a.haml
%p ä
$ haml a.haml
<p>ä</p>
```

Could you create Gist or GitHub repository which reproduces the problem?

**Comment by farbexot** [comment]
Alright screw me. 

So, when I try to compile a haml file with Terminal everything works fine (as you posted).
I use Sublime as my editor and build with a script which looks like:

`{
    "shell_cmd": "haml $file_name ${file_base_name}.html"
}`

which is basically the same. However this problem occurs. Same problems occurs when I used [Prepros](https://prepros.io) as my compiler ... I wasn't able to compile texts with umlauts.

**Comment by k0kubun** [comment]
As it's not reproductive only with Haml, it seems that third party (Sublime's) issue.

I'm sorry but I close this until we get reproductive script depending on only Haml. Probably it's better to report this to Prepros instead.

**Comment by farbexot** [comment]
Hi! I found a solution!
This thread https://github.com/at-import/Singularity/issues/207 recommended putting `Encoding.default_external = 'UTF-8'` to their config.rb file. Even though this isn't haml ... I gave it a try adding the line to haml.rb located at /Library/Ruby/Gems/2.0.0/gems/haml-5.0.2/lib/ - I have no compiling errors! I guess this should fix the Prepros problem aswell.

**Comment by k0kubun** [comment]
Ah, that's it. 

```
$ cat a.haml
%p ä
$ LANG=C haml a.haml
Haml error on line 57: Invalid US-ASCII character "\xC3"
  Use --trace for backtrace.
```

But it's more like your environment's locale or Ruby's problem, not Haml's one.

**Comment by mattwildig** [comment]
[Haml supports Ruby style encoding headers](http://haml.info/docs/yardoc/file.REFERENCE.html#encodings), so you can do (the header needs to be the very first line):

```haml
-#encoding: utf-8
%p ä
```

and then (which should also work from Sublime):

```
$ LANG=C haml a.haml
<p>ä</p>
```

and will save you editing installed files.

Of course this is really a bit of a hack, as there is nothing stopping you from having that header but saving the file with a different encoding, which will produce a similar error. For example if I save the file as ISO-8859-1 but keep the UTF-8 header I get:

```
Haml error on line 57: Invalid UTF-8 character "\xE4"
  Use --trace for backtrace.
```

This is generally a tricky issue that I’ve seen before in various places, e.g. [this issue in Tilt](https://github.com/rtomayko/tilt/issues/75).

**Comment by farbexot** [comment]
`-#encoding: utf-8
%p ä`

is also working without the need of installed files. Thanks! :)
