### ISSUE TITLE
%img changes & to &amp;

### ISSUE THREAD

**Issue by skocic-ye** [haml/haml#959]
Is this desired behaviour?
WHEN 
```haml
%img(src="http://www.facebook.com?a=b&c=d")
```
THEN
```html
<img src='http://www.facebook.com?a=b&amp;c=d'>
```
which alters the url

**Comment by k0kubun** [comment]
Desired. It's HTML escape and unescaped when it's read by browser.

**Comment by k0kubun** [comment]
Option to disable it: http://haml.info/docs/yardoc/Haml/Options.html#escape_attrs-instance_method
