### ISSUE TITLE
frozen_string_literal: false

### ISSUE THREAD

**Issue by oniofchaos** [haml/haml#962]
There's a handful of files that have this set to false, which means all strings not explicitly frozen get re-allocated each time they're referenced, leading to increased memory usage and performance loss. See https://github.com/haml/haml/pull/961 for the effort required to manually go through and freeze all the untouched strings.

I'd love to work on getting this set to true in all of these files, but need some assistance in understanding these code files and how to best approach fixing the in-place string editing. If anyone with some understanding of the codebase wants to assist it would be much appreciated.

https://github.com/haml/haml/blob/b61c6bc2c53e8a5d3c11e2d76c7cfde75cf941ab/lib/haml/helpers.rb
https://github.com/haml/haml/blob/05b5385e31c62eaf0705246b2d2c1475d5d13c78/lib/haml/generator.rb
https://github.com/haml/haml/blob/05b5385e31c62eaf0705246b2d2c1475d5d13c78/lib/haml/temple_engine.rb
https://github.com/haml/haml/blob/d84d4db0708a916a853243bb78f717c2ef986a29/lib/haml/compiler.rb
https://github.com/haml/haml/blob/a20dbbc7aaf9b4fcf51584f369f89a6b2f08ad4d/lib/haml/util.rb
https://github.com/haml/haml/blob/8f207073c2e0e2bc296f18424b3fec3dfe659674/lib/haml/engine.rb
https://github.com/haml/haml/blob/e115f796b10799d72d4f811c55d08a352c3ca6c5/lib/haml/filters.rb
https://github.com/haml/haml/blob/7e4dbacee1b54396d44286018dfaff362dee5b73/lib/haml/parser.rb

**Comment by k0kubun** [comment]
resolved by https://github.com/haml/haml/pull/967
