### ISSUE TITLE
ISSUE: HTML5 with IE 11

### ISSUE THREAD

**Issue by cuihq** [haml/haml#969]
## ISSUE 

IE 11 don't load `CSS` file.

## CAUSE

 `!!!` generate `<!DOCTYPE html>`. 

## SOLUTION

 `!!!` generate `<!DOCTYPE>`.  

> [Code](https://github.com/haml/haml/blob/master/lib/haml/compiler.rb#L189)
> [Code](https://github.com/haml/haml/blob/master/lib/haml/compiler.rb#L195)

**Comment by k0kubun** [comment]
`<!DOCTYPE>` is invalid syntax and `<!DOCTYPE html>` is correct. Try validating it on W3C https://validator.w3.org/check. To support IE11, you should specify X-UA-Compatible instead.

Also, you can generate `<!DOCTYPE>` by directly writing `<!DOCTYPE>`. It should be sufficient for your use case if you really want such output.

**Comment by cuihq** [comment]
I has sepcitied X-UA_compatible, but it had no effect.

```haml
%meta(http-equiv='X-UA-Compatible' content='IE=edge')
%meta(http-equiv='X-UA-Compatible' content='IE=8')
```

So, I drectly wirting ```<!DOCTYPE>``` to support IE11.
```ruby
class Haml::Compiler
  def text_for_doctype
    '<!DOCTYPE>'
  end
end
```

Thanks a lot.
