### ISSUE TITLE
Using text on the same line and nested tags at the same time

### ISSUE THREAD

**Issue by bogdan** [haml/haml#971]
HAML allows you to either specify tag content on the same line like:

``` haml
%h3 Hello
```

Or using nested content

``` haml
%h3
  Hello
```

Why can't I use them at the same time:

``` haml
%p Lorem ipsum
  Dolor et

%ol
  %li first section:
    %ol
      %li first subsection
      %li second subsection
```

I think this is a valid HAML syntax extension.

**Comment by Ana06** [comment]
I don't think it is. I think the inline syntax can only be used if you only have one thing. You can use:

```
%p 
  Lorem ipsum
  Dolor et
```

**Comment by k0kubun** [comment]
As of now, that's invalid syntax and I think https://github.com/haml/haml/issues/971#issuecomment-441996201 is simpler anyway in this particular use case.
