### ISSUE TITLE
Gem depends on #inspect producing valid Ruby code

### ISSUE THREAD

**Issue by ngollan** [haml/haml#972]
Trying to produce shorter/prettier (no accounting for taste) inspect output and overriding `TrueClass/FalseClass#inspect` breaks "optimisation" with something like:

```
undefined local variable or method `⊤' for #<Haml::AttributeCompiler:0x007f1a0304c648>
```

in `Haml::AttributeCompiler#static_build`.

I have true/false represented by "⊤" and "⊥" via

```ruby
TrueClass.class_eval do
  def inspect
    "⊤"
  end
end

FalseClass.class_eval do
  def inspect
    "⊥"
  end
end
```

**Comment by hcatlin** [comment]
@ngollan do you have a sample of this override? Or, a gem that does this?

**Comment by k0kubun** [comment]
> do you have a sample of this override? Or, a gem that does this?

Having the attached code somewhere would reproduce this. It's my fault on Haml 5.

```rb
TrueClass.class_eval do
  def inspect
    "⊤"
  end
end

FalseClass.class_eval do
  def inspect
    "⊥"
  end
end
```

**Comment by ngollan** [comment]
I had not expected this "issue" to get fixed ;-) Anyway, the test in the referenced commit overrides `TrueClass#inspect` twice instead of having one override for `FalseClass`.

**Comment by k0kubun** [comment]
> the test in the referenced commit overrides TrueClass#inspect twice instead of having one override for FalseClass.

Good eye! Fixed it https://github.com/haml/haml/commit/b56453709139857d48037096ceeb4c2dc58f4860
