### ISSUE TITLE
haml did not translate <transition >

### ISSUE THREAD

**Issue by grasp** [haml/haml#973]
when I apply this line

%transition{"name"=>"my-transition","enter-class"=>"animated shake","mode"=>"out-in"}
   xxx
   xxx

haml  just ignore the %transition , and did nothing 

if we change transition to transition1 or transition2 , than haml will do compile.  

This will result we could not apply transition with vuejs.

**Comment by k0kubun** [comment]
```
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

$ haml -v
Haml 5.0.4

$ cat a.haml
%transition{"name"=>"my-transition","enter-class"=>"animated shake","mode"=>"out-in"}
xxx
xxx

$ haml a.haml
<transition enter-class='animated shake' mode='out-in' name='my-transition'></transition>
xxx
xxx
```

Properly rendered. Please provide more information to reproduce the issue.
