### ISSUE TITLE
multiline bug ?

### ISSUE THREAD

**Issue by rubydesign** [haml/haml#976]
Hi,
i've been using haml for years: great. So if i can do something to help fix this, i will.

I recently got into vue, so off course i write vue app and component templates in haml. Which works well.
Even more recently i got into svg creation with vue. Svg is off course great in that it too is xml, but the spec is so so. Some transforms and specifically polylines get long, no avoiding that.

```
          %polyline{":points":"`0,0 |
                                ${frame.width},0 |
                                ${frame.width},${frame.size} |
                                0,${frame.size}`"} |

          %polyline{":points":"`${frame.width - frame.size},${frame.size} |
                                ${frame.width},${frame.size} |
                                ${frame.width},${frame.height} |
                                ${frame.width - frame.size},${frame.height}`"} |
```
Now i hope my understanding is correct, in that the above should convert to two polyline elements with long points attributes.

But what happens is that the second becomes text of the first. (Vue transforms the values for the first element)

```
  <polyline points="0,0 300,0 300,15 0,15">
    %polyline{":points":"`${frame.width - frame.size},${frame.size} ${frame.width},${frame.size} ${frame.width},${frame.height} ${frame.width - frame.size},${frame.height}`"}
  </polyline>
```
The inner element should have been converted to html by haml, but didn't. 

If this is my fault, i'd be happy to hear how i should write this code.

Using haml 5.0.4 and ruby 2.4.1

**Comment by hcatlin** [comment]
This does look like a bug. The "wall" on the left should get broken by another `%`.

**Comment by hcatlin** [comment]
Next step here should be the creation of a haml-spec test for this.

**Comment by mattwildig** [comment]
I think this is actually intentional; see #42.  If this is changed so that e.g. a blank line or a line with the same indentation ends the previous multiline block it should probably be treated as a breaking change.

The current “official” way to have two multiline blocks next to each other like this is to separate them with a comment:

```haml
%polyline{points: "`0,0 |
                    ${frame.width},0 |
                    ${frame.width},${frame.size} |
                    0,${frame.size}`"} |
-#
%polyline{points: "`${frame.width - frame.size},${frame.size} |
                    ${frame.width},${frame.size} |
                    ${frame.width},${frame.height} |
                    ${frame.width - frame.size},${frame.height}`"} |
```

which produces

```html
<polyline points='`0,0 ${frame.width},0 ${frame.width},${frame.size} 0,${frame.size}`'></polyline>
<polyline points='`${frame.width - frame.size},${frame.size} ${frame.width},${frame.size} ${frame.width},${frame.height} ${frame.width - frame.size},${frame.height}`'></polyline>
```

(P.S. you don’t need `":points":`, just `points:`.)

**Comment by rubydesign** [comment]
It not a bug. It's a feature!

I do actually subscribe to that, and thanks for the workaround.
It's the first time in many years i even use multi line, and it's only because of the strange combination of vue and svg. It would maybe be better to render this example in code.
But i have moved on to proper 3d, instead of messing with svg, so i'll close this.

PS: the `:points` is a vue syntax which means the attribute will be evaluated. Without the colon it would be a literal and not make much sense. But thanks.

**Comment by hcatlin** [comment]
And... I come in looking like an idiot.

I thought the 'wall' (as we used to lovingly describe it) had to be unbroken to keep going.

Aka,

```
this |
is |
a |
wall|

but|
this|
is|
broken|
```

I'd think if you really wanted that wall, you'd put a pipe on the empty line. And, if you wanted a printed pipe, you'd do `\|`

**Comment by mattwildig** [comment]
I agree, having the two blocks separated with a blank line suggests that the first block is finished. The current behaviour is somewhat unexpected and I think changing it would make sense.
