### ISSUE TITLE
Interpolation with question mark without quotes in :javascript filter screws up highlighting

### ISSUE THREAD

**Issue by FunkyloverOne** [haml/haml#978]
This is related to https://github.com/HarlemSquirrel/language-haml/issues/72

Here's code which is a **valid ruby**, and works as expected, but for some reason breaks highlighting everywhere, and is kinda invalid haml:

```haml
:javascript
  var booleanVar = #{boolean_method?};
.class-with-number-6-here
  .class-with-number-12.another-class
    -# commented out code
    -# - if @bool_variable
    -#   .col-xs-12
    -#     number with unit 12kg
    text after quote 'lorem ipsum
    a bit more of text
  .some-class
    = form_for @user do |f|
      .label Email
      = f.email_field :email
      - if @bool_variable
        ...
```
Here's quoted version for comparison:

```haml
:javascript
  var booleanVar = "#{boolean_method?}";
.class-with-number-6-here
  .class-with-number-12.another-class
    -# commented out code
    -# - if @bool_variable
    -#   .col-xs-12
    -#     number with unit 12kg
    text after quote 'lorem ipsum
    a bit more of text
  .some-class
    = form_for @user do |f|
      .label Email
      = f.email_field :email
      - if @bool_variable
        ...
```

**Comment by k0kubun** [comment]
Wrong place to report. This repository is not related to the highlight at all.

If GitHub doesn't change its backend from 2014, it may be pygments https://bitbucket.org/birkenfeld/pygments-main.
I previously implemented Slim syntax highlight https://bitbucket.org/birkenfeld/pygments-main/pull-requests/366/add-slimlexer and it seems to be applied to GitHub.
