### ISSUE TITLE
Proposal: Multiline Attributes

### ISSUE THREAD

**Issue by hcatlin** [haml/haml#981]
Following off of the discussion in #976....

As I read back on those old comments and in the documentation... we only were thinking of the wall for content text blobs to stop people from writing too much 'pure ruby' in weird places. That's why we made it hard. Actually, we almost were explicitly thinking of things after the `=`

However... stylistically, I think we ended up punishing interesting (and pretty!) Haml-styling possibilities. Consider this.

```
%div{
  myAttribute: "blue",
  anotherAttribute: "red",
  moreStuff: "My text is #{@var}",
}
  I am some nested content.
```

This doesn't seem ugly to me. That's not something we really considered at the time, as we were just trying to keep logic out of the templates, but, I don't think we were thinking of a React-y world where it was a good idea to have multiple attributes on an element.

Maybe we should be more lax (though, not with the indentation!) about what happens between the `{` and the `}`?

**Comment by hcatlin** [comment]
Interesting. I mean, having the trailing comma is pretty en-vogue these days. I just saw it barf on that when I tried it.

I found this in the docs ```In addition, sometimes you need to call Ruby methods or declare data structures that just need a lot of template information. So data structures and functions that require lots of arguments can be wrapped over multiple lines, as long as each line but the last ends in a comma (see Inserting Ruby).```

I guess, technically, putting the `}` on it's own line without a comma fits that definition, but seems like an accidental support for training commas.

**Comment by archonic** [comment]
I think this would be a good addition, particularly as Stimulus and it's many data-attributes become more common place.

**Comment by hcatlin** [comment]
The absolutely amazing @k0kubun added this in!
