### ISSUE TITLE
white-space node inserted when using `{ }` block form but using `do..end` block form it doesn't

### ISSUE THREAD

**Issue by jiggneshhgohel** [haml/haml#991]
**haml-rails (1.0.0)**
**haml (5.0.4)**
**bootstrap-sass (3.3.7)**
**rails (5.0.0.1 )**
**ruby (2.3.2)**

--------------------------------------

**Snippet-1**

```
.form-group
  .col-md-10.col-md-offset-3
    = button_tag(type: 'button', class: "btn custom-button" ) do
      = "Add"

    = link_to( "Cancel",
               some_path,
               class: "btn cancel-button")
```

renders as 

**1.png**

![1](https://user-images.githubusercontent.com/10440841/44786180-ef2b8280-abb0-11e8-8a34-bca9c8af6f2b.png)

**Snippet-2**

```
.form-group
  .col-md-10.col-md-offset-3
    = button_tag(type: 'button', class: "btn custom-button" ) { "Add" }

    = link_to( "Cancel",
               some_path,
               class: "btn cancel-button")
```

renders as

**2.png**

![2](https://user-images.githubusercontent.com/10440841/44786204-010d2580-abb1-11e8-9a4e-41ade8abc684.png)

As can be seen the block syntax used is causing different renderings. My expectation was   **Snippet-1** to be rendered as shown under **2.png** . 

Can anybody please help me understand what's going on which is causing the white-space-node to be automatically inserted in DOM while rendering **Snippet-2**, but preventing that from happening with **Snippet-1**?

**Comment by k0kubun** [comment]
Please try using `<` and/or `>`, like `.col-md-10.col-md-offset-3><`. Either of the operations (sorry, I forgot) is supposed to eliminate a whitespace inside an element.
