### ISSUE TITLE
attribute with safe-buffer containing a apostrophe is not escaped

### ISSUE THREAD

**Issue by timdiggins** [haml/haml#993]
I've run into an issue when embedding html in an attribute in haml. 

if the attribute is a `SafeBuffer` (or otherwise `html_safe?` already) then any apostrophes don't get converted to `&#39`. I thought it should -- because although it is marked html_safe, that doesn't necessarily mark it as attribute-safe (hence the need for `'` to `&#39` conversion).

Is this something Haml should support? I've got a test for it (but no clue how to implement as yet). 

The alternative is that this change has to be done within the template itself (with something like `my_safe_buffer.gsub("'", "&#39;").html_safe`)

**Comment by timdiggins** [comment]
Yes of course, here's a tiny snippet:

    %a{data: { content: simple_format(some_comment)}}

but if `some_comment` includes a `'` (single quote / apostrophe) then the html is broken (and the browser typically renders some of the data-comment in the page.

So I have to do:

    %a{data: { content: simple_format(some_comment).gsub("'", "&#39;").html_safe}}

I've written up a test to demonstrate this:

https://github.com/haml/haml/compare/master...timdiggins:escape-apostrophe-in-attribute-when-safebuffer?expand=1#diff-329388b93ea342ebfe212a3023c624cdR351

More generally, Haml knows when it's in attribute context, and it knows what quote (single/double) it will be using to wrap the attribute, and it can (as demonstrated) convert the single quotes for an raw string / unsafe buffer. The safe buffer is guaranteeing everything is *html* safe, but not *attribute* safe (hence escaping of the wrapping quote is required).

**Comment by jdelStrother** [comment]
I also ran into this when stuffing some HTML into a data attribute with something like:

```haml
%div{"data-success" => render("success_button")}
```

which outputs something along the lines of

```html
<div data-success="<button ....
```

Sounds like it's a wontfix for haml 5, fingers cross for haml 6... https://github.com/haml/haml/issues/977
